apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: travelmate-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: travelmate-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: travelmate-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: travelmate-frontend
