apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s
  - ingress.yaml
  - disruption-budgets.yaml
patches:
  - path: configmap-patch.yaml
  - path: frontend-service-patch.yaml
  - path: backend-object-storage-patch.yaml
  - path: uploads-pvc-delete.yaml
