apiVersion: v1
kind: ConfigMap
metadata:
  name: travelmate-microservices-config
  labels:
    app.kubernetes.io/name: travelmate-microservices-config
    app.kubernetes.io/part-of: travelmate
data:
  CORS_ALLOWED_ORIGINS: http://localhost:30080,http://127.0.0.1:30080
  REDIS_HOST: travelmate-redis
  REDIS_PORT: "6379"
  IDENTITY_SERVICE_URL: http://identity-service:8081
  LOCAL_SERVICE_URL: http://local-service:8083
  AI_SERVICE_URL: http://ai-service:8084
  OUTBOX_DISPATCHER_ENABLED: "true"
  MYBATIS_LOG_IMPL: org.apache.ibatis.logging.nologging.NoLoggingImpl
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError
  IDENTITY_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_identity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  IDENTITY_DATASOURCE_USERNAME: travelmate_identity_app
  TRAFFIC_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_traffic?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  TRAFFIC_DATASOURCE_USERNAME: travelmate_traffic_app
  LOCAL_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_local?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  LOCAL_DATASOURCE_USERNAME: travelmate_local_app
  AI_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  AI_DATASOURCE_USERNAME: travelmate_ai_app
