apiVersion: v1
kind: ConfigMap
metadata:
  name: travelmate-microservices-config
  labels:
    app.kubernetes.io/name: travelmate-microservices-config
    app.kubernetes.io/part-of: travelmate
data:
  CORS_ALLOWED_ORIGINS: http://localhost:30080,http://127.0.0.1:30080
  REDIS_HOST: travelmate-redis
  REDIS_PORT: "6379"
  IDENTITY_SERVICE_URL: http://identity-service:8081
  LOCAL_SERVICE_URL: http://local-service:8083
  AI_SERVICE_URL: http://ai-service:8084
  COMMUNITY_SERVICE_URL: http://community-service:8085
  OPS_SERVICE_URL: http://ops-service:8086
  OUTBOX_DISPATCHER_ENABLED: "true"
  MYBATIS_LOG_IMPL: org.apache.ibatis.logging.nologging.NoLoggingImpl
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70.0 -XX:+ExitOnOutOfMemoryError
  IDENTITY_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_identity?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  IDENTITY_DATASOURCE_USERNAME: travelmate_identity_app
  TRAFFIC_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_traffic?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  TRAFFIC_DATASOURCE_USERNAME: travelmate_traffic_app
  LOCAL_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_local?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  LOCAL_DATASOURCE_USERNAME: travelmate_local_app
  AI_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_ai?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  AI_DATASOURCE_USERNAME: travelmate_ai_app
  COMMUNITY_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_community?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  COMMUNITY_DATASOURCE_USERNAME: travelmate_community_app
  OPS_DATASOURCE_URL: jdbc:mysql://travelmate-mysql:3306/travelmate_ops?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  OPS_DATASOURCE_USERNAME: travelmate_ops_app
  DEEPSEEK_BASE_URL: https://api.deepseek.com
  DEEPSEEK_CHAT_COMPLETIONS_PATH: /chat/completions
  DEEPSEEK_PLAN_MODEL: deepseek-v4-flash
  DEEPSEEK_THINKING_ENABLED: "false"
  DEEPSEEK_REASONING_EFFORT: high
  AI_PLACE_VERIFICATION_ENABLED: "true"
