CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(100),
    operation VARCHAR(255),
    method VARCHAR(255),
    params CLOB,
    ip VARCHAR(64),
    time_ms BIGINT,
    status INT,
    error_msg VARCHAR(500),
    create_time TIMESTAMP
);
