CREATE TABLE IF NOT EXISTS sys_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(100),
    operation VARCHAR(255),
    method VARCHAR(255),
    params CLOB,
    ip VARCHAR(64),
    time_ms BIGINT,
    status INT,
    error_msg VARCHAR(500),
    create_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_bootstrap_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    secret_fingerprint CHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    attempt_count INT NOT NULL DEFAULT 0,
    last_attempt_ip VARCHAR(64),
    last_result VARCHAR(64),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS admin_bootstrap_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id BIGINT,
    username VARCHAR(64),
    source_ip VARCHAR(64),
    result VARCHAR(64) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_admin_bootstrap_audit_token
        FOREIGN KEY (token_id) REFERENCES admin_bootstrap_token(id)
);

CREATE TABLE IF NOT EXISTS auth_refresh_session (
    id CHAR(36) PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_hash CHAR(64) NOT NULL UNIQUE,
    token_version INT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    source_ip VARCHAR(64),
    user_agent VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP
);
