apiVersion: v1
kind: ConfigMap
metadata:
  name: travelmate-config
data:
  STORAGE_TYPE: s3
  S3_ENDPOINT: http://travelmate-minio:9000
  S3_REGION: us-east-1
  S3_BUCKET: travelmate
  S3_PUBLIC_BASE_URL: http://localhost:30900/travelmate
