apiVersion: v1
kind: Secret
metadata:
  name: travelmate-microservices-secrets
  namespace: travelmate-microservices
type: Opaque
stringData:
  mysql-root-password: replace_with_mysql_root_password
  identity-db-password: replace_with_identity_database_password
  traffic-db-password: replace_with_traffic_database_password
  local-db-password: replace_with_local_database_password
  ai-db-password: replace_with_ai_database_password
  jwt-secret: replace_with_base64_encoded_random_secret
  internal-service-token: replace_with_random_internal_service_token
  admin-register-secret: replace_with_random_admin_register_secret
