apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: travelmate
resources:
  - namespace.yaml
  - configmap.yaml
  - storage.yaml
  - mysql.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
