-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: ai
-- This file contains schema only; demo seed data remains in the monolith baseline.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `travelmate_ai` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `travelmate_ai`;
-- tm_ai_plan
CREATE TABLE IF NOT EXISTS `tm_ai_plan` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `title` VARCHAR(200) COMMENT '行程标题',
  `destination` VARCHAR(100) NOT NULL COMMENT '目的地',
  `start_date` DATE COMMENT '出发日期',
  `days` INT NOT NULL COMMENT '天数',
  `budget` DECIMAL(10,2) COMMENT '预算',
  `people_count` INT DEFAULT '1' COMMENT '出行人数',
  `preferences` VARCHAR(500) COMMENT '偏好标签(逗号分隔)',
  `plan_content` LONGTEXT COMMENT 'AI生成的行程JSON内容',
  `status` TINYINT(1) DEFAULT '1' COMMENT '1-有效, 0-删除',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI行程规划记录表';

-- tm_ai_chat
CREATE TABLE IF NOT EXISTS `tm_ai_chat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT COMMENT '用户ID(可匿名)',
  `session_id` VARCHAR(100) NOT NULL COMMENT '会话ID',
  `role` VARCHAR(20) NOT NULL COMMENT 'user/assistant',
  `content` TEXT NOT NULL COMMENT '消息内容',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_session` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI客服对话记录表';

-- tm_notification
CREATE TABLE IF NOT EXISTS `tm_notification` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '接收用户ID',
  `type` VARCHAR(50) NOT NULL COMMENT '通知类型(order/comment/like/system)',
  `title` VARCHAR(200) NOT NULL COMMENT '通知标题',
  `content` TEXT COMMENT '通知内容',
  `action_url` VARCHAR(300) DEFAULT NULL COMMENT '点击跳转路径',
  `is_read` TINYINT(1) DEFAULT '0' COMMENT '0-未读, 1-已读',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='站内通知表';

-- tm_private_message
CREATE TABLE IF NOT EXISTS `tm_private_message` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `sender_id` BIGINT NOT NULL COMMENT '发送者ID',
  `receiver_id` BIGINT NOT NULL COMMENT '接收者ID',
  `content` VARCHAR(1000) NOT NULL COMMENT '消息内容',
  `read_status` TINYINT(1) DEFAULT '0' COMMENT '0-未读, 1-已读',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  `deleted` TINYINT(1) DEFAULT '0' COMMENT '逻辑删除',
  PRIMARY KEY (`id`),
  KEY `idx_sender_receiver` (`sender_id`, `receiver_id`),
  KEY `idx_receiver_read` (`receiver_id`, `read_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户私信消息表';

-- tm_private_contact
CREATE TABLE IF NOT EXISTS `tm_private_contact` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `contact_user_id` BIGINT NOT NULL COMMENT '联系人用户ID',
  `last_message_id` BIGINT DEFAULT NULL COMMENT '最后一条消息ID',
  `unread_count` INT DEFAULT '0' COMMENT '未读数',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_private_contact` (`user_id`, `contact_user_id`),
  KEY `idx_private_contact_update` (`user_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户私信联系人表';

-- tm_ai_consumed_event
CREATE TABLE IF NOT EXISTS `tm_ai_consumed_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(36) NOT NULL COMMENT '已消费的全局事件ID',
  `event_type` VARCHAR(100) NOT NULL COMMENT '事件类型',
  `processed_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_consumed_event_id` (`event_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI消息服务幂等消费记录';
