-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: community demo seed data for local integration and E2E only.

SET NAMES utf8mb4;
USE `travelmate_community`;

INSERT INTO `tm_post` (`id`, `user_id`, `title`, `content`, `images`, `destination`, `tags`, `like_count`, `comment_count`, `collect_count`, `view_count`, `status`, `source_name`, `source_url`, `data_checked_date`) VALUES
(1, 3, '北京5天｜中轴线故宫长城不绕路路线', '这次北京行程按“核心景点分散预约”的思路安排，前两天留给升旗、天安门、故宫和国家博物馆，故宫建议午门进、神武门出，下午接景山看中轴线视角会很顺。第三天去八达岭长城，早班高铁到八达岭长城站最省心，返城后只安排鸟巢、水立方夜景，不再塞博物馆。第四天放慢节奏走颐和园、圆明园和高校周边，第五天用恭王府、什刹海、鼓楼、雍和宫、南锣鼓巷收尾。北京很多场馆都需要提前预约，住宿建议放在二环或地铁 2/4/8 号线附近，每天少换一次线会轻松很多。', '/images/seed/beijing.svg,/images/seed/beijing.svg,/images/seed/beijing.svg', '北京', '北京,故宫,八达岭长城,颐和园,中轴线', 9224, 108, 9174, 27600, 1, '公开路线资料整理', NULL, '2026-05-21'),
(2, 4, '上海1天｜武康路静安寺外滩陆家嘴', '上海一日游不要贪多，最好把路线压成一条从西到东的 citywalk。上午从武康大楼开始，沿武康路慢慢走到安福路一带，咖啡店和老洋房都适合边走边拍；中午转到静安寺或南京西路吃饭，下午去豫园和城隍庙，留 1.5 小时足够。傍晚 18:30 后到外滩看亮灯，天气好可以坐轮渡到陆家嘴，十几分钟就能换到浦东视角。虹桥进出城尽量避开晚高峰，外滩人多时不要只挤观景平台，往十六铺方向走会舒服一些。', '/images/seed/shanghai.svg,/images/seed/shanghai.svg', '上海', '上海,外滩,陆家嘴,武康路,citywalk', 5725, 16, 5034, 17200, 1, '公开路线资料整理', NULL, '2026-05-21'),
(3, 3, '三亚蜈支洲岛｜玻璃海环岛路线', '蜈支洲岛适合放在天气最好的那一天，海水颜色、能见度和拍照效果都很看阳光。建议早上第一批上岛，先坐观光车走海洋之星、观日岩、情人谷、情人岛几个远点，中午回到码头附近吃饭休息，下午再沿灯塔、情人桥和沙滩慢慢拍照。岛上水上项目排队时间不短，潜水、摩托艇和拖伞最好只选一两个，不然会把整天都耗在等候区。防晒衣、拖鞋、防水袋和少量现金很实用，岛上餐饮价格偏高，可以提前带水和简单零食。', '/images/seed/sanya.svg,/images/seed/sanya.svg', '三亚', '三亚,蜈支洲岛,亚龙湾,海岛,玻璃海', 5283, 149, 4513, 15800, 1, '公开路线资料整理', NULL, '2026-05-21'),
(4, 4, '成都周边1天｜熊猫谷都江堰轻量路线', '成都周边如果只留一天，熊猫谷加都江堰比市区熊猫基地更适合错峰。早上从春熙路附近出发，地铁到犀浦后换高铁到离堆公园，先去仰天窝广场拍照，再打车到熊猫谷，上午看熊猫活动概率更高。午餐可以放在灌县古城，下午从秦堰楼方向进入都江堰，一路往下走二王庙、安澜索桥、鱼嘴、飞沙堰、宝瓶口和离堆公园，基本不走回头路。傍晚南桥亮灯很有氛围，但返程高铁要提前看班次，周末不要卡最后一班。', '/images/seed/chengdu.svg,/images/seed/chengdu.svg', '成都', '成都,熊猫谷,都江堰,灌县古城,周边游', 2242, 94, 3413, 9800, 1, '公开路线资料整理', NULL, '2026-05-21'),
(5, 2, '丽江2天｜玉龙雪山蓝月谷白沙古镇', '丽江两天更适合把雪山和古城分开走。第一天早起去玉龙雪山，索道票一定要提前抢，体力一般可以选云杉坪或牦牛坪，想冲海拔再考虑冰川公园；蓝月谷放在下山后，晴天水色会非常漂亮。下午回束河古镇吃饭休息，比大研古城安静一些。第二天看天气决定要不要去东巴谷看日照金山，再去白沙古镇喝咖啡、看雪山和纳西院落，下午回丽江古城逛现文巷、大研花巷和狮子山。高海拔行程不要硬撑，氧气、保暖外套和甜食都要提前备好。', '/images/seed/attraction.svg,/images/seed/attraction.svg', '丽江', '丽江,玉龙雪山,蓝月谷,白沙古镇,高原旅行', 2518, 10, 2160, 7600, 1, '公开路线资料整理', NULL, '2026-05-21')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `images` = VALUES(`images`),
  `destination` = VALUES(`destination`),
  `tags` = VALUES(`tags`),
  `like_count` = VALUES(`like_count`),
  `comment_count` = VALUES(`comment_count`),
  `collect_count` = VALUES(`collect_count`),
  `view_count` = VALUES(`view_count`),
  `status` = VALUES(`status`),
  `source_name` = VALUES(`source_name`),
  `source_url` = VALUES(`source_url`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_post` (`id`, `user_id`, `title`, `content`, `images`, `destination`, `tags`, `like_count`, `comment_count`, `collect_count`, `view_count`, `status`, `source_name`, `source_url`, `data_checked_date`) VALUES
(6, 3, '重庆3天2晚｜洪崖洞山城步道轻松版', '重庆三天两晚建议住解放碑、较场口或临江门附近，吃饭、看夜景和坐轨道交通都方便。第一天把解放碑、八一好吃街、洪崖洞和千厮门大桥放在一起，白天不用太赶，傍晚再去洪崖洞外侧找机位，亮灯后从桥上看江景更完整。第二天走鹅岭二厂、李子坝、山城步道、十八梯和白象居，几个点都要上下坡，鞋子一定要舒服，中间可以在观音桥或较场口安排一顿火锅。第三天按返程时间选择磁器口或观音桥，行李最好寄存在酒店或地铁站。重庆看地图距离不远，但爬坡、排队和换乘都很耗体力，每天留一点空档会舒服很多。', '/images/seed/chongqing.svg,/images/seed/chongqing.svg', '重庆', '重庆,洪崖洞,山城步道,三天两晚,夜景', 1759, 86, 1480, 8200, 1, '公开路线资料整理', NULL, '2026-05-21'),
(7, 4, '重庆特种兵路线｜轻轨夜景火锅都要有', '这条重庆周末路线适合只有两天一晚、又想把经典点位都看一眼的人。第一天上午先去李子坝看轻轨穿楼，随后到鹅岭二厂、鹅岭公园一带慢慢走，午后切到湖广会馆和白象居，老建筑、江面和居民楼层次很适合拍照。傍晚去来福士或朝天门看两江交汇，晚上再到洪崖洞和千厮门大桥，灯光比白天更有山城氛围。第二天可以睡到自然醒，吃一顿小面或江湖菜，再去山城步道、十八梯补一段 citywalk。热门机位不用死排，重庆的惊喜经常在路边楼梯、天桥和转角。', '/images/seed/chongqing.svg,/images/seed/chongqing.svg', '重庆', '重庆,李子坝,火锅,夜景,周末游', 1245, 54, 1190, 6900, 1, '公开路线资料整理', NULL, '2026-05-21'),
(8, 2, '厦门3天2晚｜鼓浪屿沙坡尾环岛路', '厦门三天两晚可以按“老城、海岛、海边”来分。第一天下午到达后先去中山路和八市，海鲜小吃和骑楼街景都集中，傍晚转到沙坡尾、演武大桥观景平台和双子塔周边，晚上不必再跑太远。第二天预留给鼓浪屿，船票要提前约，建议从三丘田码头进岛，沿着最美转角、日光岩周边、菽庄花园和海边步道慢慢走，岛上岔路多，留半天以上才不会只顾赶路。第三天走南普陀、厦大白城、胡里山炮台和环岛路，天气好可以租车或骑行一小段。厦门节奏适合慢下来，轮渡时间、海风和阵雨都要提前看。', '/images/seed/coast.svg', '厦门', '厦门,鼓浪屿,沙坡尾,环岛路,海边', 7270, 211, 6380, 26800, 1, '公开路线资料整理', NULL, '2026-05-21'),
(9, 3, '江南串线｜杭州绍兴乌镇苏州上海', '江南多城串线建议从杭州进、上海出，中间尽量用高铁和短途打车衔接，不要每天拖着行李换太远。杭州可以留一天半，白天走西湖、柳浪闻莺和湖滨，晚上看钱塘江或武林夜景；第二站到绍兴，鲁迅故里、仓桥直街、书圣故里和黄酒小馆都集中，节奏比杭州慢。乌镇适合住一晚，傍晚进西栅看夜景，第二天早上再拍清净的桥和河道。之后到苏州，把拙政园、苏州博物馆、平江路和山塘街放在同一天，最后用上海外滩、陆家嘴和武康路收尾。城市多时最容易累，酒店尽量选在高铁站或地铁换乘点附近，少折返就是省体力。', '/images/real/posts/jiangnan-west-lake.jpg', '江南', '杭州,绍兴,乌镇,苏州,上海,江南路线', 587, 32, 520, 4100, 1, '公开路线资料整理', NULL, '2026-05-21'),
(10, 4, '暑期热门旅行地图｜9城灵感清单', '暑期选目的地可以先按旅行目标分组，而不是只看热度。第一次带家人出游，北京适合看故宫、长城和博物馆，西安适合兵马俑、城墙和大唐不夜城，南京适合中山陵、南京博物院和秦淮河，文化线比较完整。想看海可以选厦门、青岛、三亚，厦门轻松，青岛城市和海岸线结合得好，三亚更适合度假酒店和海岛项目。喜欢吃喝和城市烟火气，成都、重庆、长沙都很稳，但夏天要注意高温和排队。真正订票前建议先看天气、门票预约、酒店位置和每天交通余量，把必去点控制在 2 到 3 个，体验会比满地图打卡更真实。', '/images/seed/beijing.svg,/images/seed/qingdao.svg,/images/seed/chongqing.svg', '全国', '暑期旅行,城市清单,亲子,海边,旅行灵感', 1397, 74, 1280, 7600, 1, '公开路线资料整理', NULL, '2026-05-21')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `images` = VALUES(`images`),
  `destination` = VALUES(`destination`),
  `tags` = VALUES(`tags`),
  `like_count` = VALUES(`like_count`),
  `comment_count` = VALUES(`comment_count`),
  `collect_count` = VALUES(`collect_count`),
  `view_count` = VALUES(`view_count`),
  `status` = VALUES(`status`),
  `source_name` = VALUES(`source_name`),
  `source_url` = VALUES(`source_url`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_post` (`id`, `user_id`, `title`, `content`, `images`, `destination`, `tags`, `like_count`, `comment_count`, `collect_count`, `view_count`, `status`, `source_name`, `source_url`, `data_checked_date`) VALUES
(11, 2, '南京2天1晚｜博物院夫子庙中山陵', '南京两天一晚适合住新街口、夫子庙或大行宫，地铁换乘方便，晚上吃饭也不愁。第一天上午留给南京博物院，展厅很大，最好提前预约并预留 3 小时；午后可以去总统府，或者转到老门东、中华门一带慢慢走。傍晚到夫子庙和秦淮河，不一定要排游船，沿河散步、看灯和找小吃也很有南京味。第二天早起去中山陵，台阶多但视野开阔，音乐台看鸽子要看当天开放和天气，时间宽裕再接玄武湖或鸡鸣寺。南京很多景点周末客流明显，博物馆、热门餐厅和中山陵接驳都要提前留时间。', '/images/seed/nanjing.svg', '南京', '南京,夫子庙,南京博物院,中山陵,周末游', 1830, 64, 1660, 9200, 1, '公开路线资料整理', NULL, '2026-05-21'),
(12, 3, '苏州1天｜拙政园平江路山塘街', '苏州一日游最舒服的方式是只抓住古城核心，不把同类园林塞太多。早上开园后先进拙政园，游客少、光线也柔和，出来后可以顺路看苏州博物馆外观或提前预约进馆。午后沿平江路慢慢走，茶馆、评弹、小桥和水巷都适合放慢速度，中间可以绕到双塔市集吃点小吃。傍晚去山塘街，看灯光倒映在河面上，比白天更有氛围。古城里打车常常不如步行和地铁稳定，行程尽量安排在同一片区，雨天带伞也比赶车更重要。', '/images/seed/garden.svg', '苏州', '苏州,拙政园,平江路,山塘街,江南', 1246, 38, 1090, 6100, 1, '公开路线资料整理', NULL, '2026-05-21'),
(13, 4, '长沙周末｜五一广场橘子洲岳麓山', '长沙周末更适合轻松吃喝，不要把每个网红店都排成任务。第一天下午到五一广场附近入住，先走黄兴路、坡子街和太平老街，晚上按队伍情况选湘菜、小吃或茶饮，热门店排队久就果断换一家。第二天上午去橘子洲，观光车能省不少脚力，夏天一定要防晒；下午到岳麓山和湖南大学，想轻松可以索道上、步行下，顺路看爱晚亭和校园街区。晚上回市区再补一顿夜宵。长沙地铁方便，但商圈人流密集，住宿选五一广场外一两站会安静很多。', '/images/seed/attraction.svg', '长沙', '长沙,橘子洲,岳麓山,五一广场,美食', 986, 41, 820, 5300, 1, '公开路线资料整理', NULL, '2026-05-21'),
(14, 2, '青岛3天｜栈桥八大关小麦岛看海', '青岛三天建议把老城、海岸线和崂山方向分开，不然每天都在跨城。第一天从栈桥、天主教堂、信号山和大学路开始，老城区坡路多但很适合慢慢走，傍晚去小鱼山或琴屿路看海。第二天安排八大关、第二海水浴场、太平角和小麦岛，天气晴的时候海水颜色很漂亮，下午风大要带外套。第三天看体力选择石老人、崂山或啤酒博物馆，想轻松就留在市区吃海鲜、逛市南老街。青岛看海很吃天气，晴天优先拍海边，阴天就换成老建筑和博物馆路线。', '/images/seed/qingdao.svg', '青岛', '青岛,栈桥,八大关,小麦岛,看海', 1468, 52, 1330, 7900, 1, '公开路线资料整理', NULL, '2026-05-21')
ON DUPLICATE KEY UPDATE
  `title` = VALUES(`title`),
  `content` = VALUES(`content`),
  `images` = VALUES(`images`),
  `destination` = VALUES(`destination`),
  `tags` = VALUES(`tags`),
  `like_count` = VALUES(`like_count`),
  `comment_count` = VALUES(`comment_count`),
  `collect_count` = VALUES(`collect_count`),
  `view_count` = VALUES(`view_count`),
  `status` = VALUES(`status`),
  `source_name` = VALUES(`source_name`),
  `source_url` = VALUES(`source_url`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_post` (`id`, `user_id`, `title`, `content`, `images`, `destination`, `tags`, `like_count`, `comment_count`, `collect_count`, `view_count`, `status`, `source_name`, `data_checked_date`) VALUES
(11, 4, '山东泰山+曲阜孔庙4天｜登顶看日出攻略',
  'Day1济南：趵突泉+大明湖+宽厚里；Day2泰山：推荐凌晨12点从红门出发徒步，爬5小时到南天门在天街等日出，日出后吃豆腐脑早餐再下山（用缆车）；Day3曲阜：三孔（孔庙孔林孔府），半天到一天即可；Day4返程。泰山登顶一定要带厚衣物，山顶夏天也只有十几度，日出前后风大刺骨。',
  '/images/seed/mountain.svg,/images/seed/mountain.svg,/images/seed/nanjing.svg',
  '泰安', '山东,泰山,泰山日出,曲阜,孔庙,济南', 11200, 247, 10800, 43000, 1, '演示游记', '2026-05-19'),

(12, 2, '武汉2天｜黄鹤楼+汉口租界+东湖绿道',
  'Day1：黄鹤楼（早9点前进景区人少）—蛇山城墙—武汉大学（需提前预约）—户部巷宵夜；Day2：汉口老租界漫步（大和街、中山大道）—黎黄陂路小吃—东湖绿道骑行（推荐磨山段）—光谷步行街。武汉地铁很方便，主要景点都能覆盖，两天完全够用，热干面和豆皮必尝。',
  '/images/seed/attraction.svg,/images/seed/attraction.svg,/images/seed/lake.svg',
  '武汉', '武汉,黄鹤楼,汉口租界,东湖,两天一夜', 6700, 158, 6400, 26000, 1, '演示游记', '2026-05-19'),

(13, 3, '苏州+周庄2天｜古典园林完整打卡',
  'Day1苏州：拙政园（7:30刚开门进最安静）—狮子林—平江路茶馆—苏博（免费需预约）—观前街；Day2周庄：早8点前进古镇人最少，走富安桥—双桥—沈厅—张厅，中午吃万三蹄，下午2点前出镇避开人流。苏州园林建议只选1-2个深度游，不要贪多导致走马观花。周庄早进早出是关键。',
  '/images/seed/garden.svg,/images/seed/garden.svg,/images/seed/attraction.svg',
  '苏州', '苏州,拙政园,周庄,园林,江南水乡', 7400, 169, 7100, 28000, 1, '演示游记', '2026-05-19'),

(14, 4, '青岛+崂山3天｜海滨城市完整路线',
  'Day1青岛市区：栈桥—小鱼山—八大关（欧式建筑群）—太平山索道—台东步行街晚餐；Day2崂山：北线巨峰，上缆车下步行，下午顺路看太清宫；Day3劈柴院早餐+中山路+博物馆（免费）+啤酒街晚餐扫货。青岛比想象中大，建议地铁为主，五四广场+海边走走必排。海鲜大排档一定要货比三家再进。',
  '/images/seed/qingdao.svg,/images/seed/qingdao.svg,/images/seed/qingdao.svg',
  '青岛', '青岛,崂山,栈桥,八大关,海鲜,啤酒', 5900, 143, 5700, 23000, 1, '演示游记', '2026-05-19'),

(15, 2, '南京2天｜中山陵+夫子庙+先锋书店',
  'Day1：中山陵（徒步博爱坊到祭堂329级台阶，背景开阔壮观）—明孝陵（石象路神兽路很出片）—紫金山步道散步；Day2：玄武湖公园（免费，环湖一圈约1小时）—台城（樱花季必来，非花季也很美）—夫子庙秦淮河—先锋书店（地下空间全国最美书店之一）。南京旅游性价比极高，博物馆基本免费。',
  '/images/seed/nanjing.svg,/images/seed/nanjing.svg,/images/seed/nanjing.svg',
  '南京', '南京,中山陵,夫子庙,玄武湖,台城,周末游', 8100, 187, 7800, 32000, 1, '演示游记', '2026-05-19')

ON DUPLICATE KEY UPDATE
  `title`             = VALUES(`title`),
  `content`           = VALUES(`content`),
  `images`            = VALUES(`images`),
  `destination`       = VALUES(`destination`),
  `tags`              = VALUES(`tags`),
  `like_count`        = VALUES(`like_count`),
  `comment_count`     = VALUES(`comment_count`),
  `collect_count`     = VALUES(`collect_count`),
  `view_count`        = VALUES(`view_count`),
  `status`            = VALUES(`status`),
  `data_checked_date` = VALUES(`data_checked_date`);
