-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: local demo seed data for local integration and E2E only.

SET NAMES utf8mb4;
USE `travelmate_local`;

INSERT IGNORE INTO `tm_hotel` (`id`, `name`, `city`, `address`, `star_rating`, `description`, `cover_img`, `lat`, `lng`, `avg_price`, `score`, `source_name`, `source_url`, `data_checked_date`) VALUES
(1, '北京国贸大酒店', '北京', '朝阳区建国门外大街1号', 5, '位于北京CBD核心地带，毗邻国贸商圈，提供顶级商务服务与城市景观。', NULL, 39.9087, 116.4575, 1580.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(2, '上海外滩华尔道夫酒店', '上海', '黄浦区中山东一路2号', 5, '位于外滩历史建筑群区域，临近黄浦江与外滩公共开放空间。', NULL, 31.2400, 121.4900, 2380.00, 4.9, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(3, '广州白天鹅宾馆', '广州', '荔湾区沙面岛南街1号', 5, '坐落于沙面岛珠江畔，是广州具有代表性的老牌高星酒店。', NULL, 23.1198, 113.2432, 1280.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(4, '成都锦江宾馆', '成都', '锦江区人民南路二段80号', 4, '位于成都市中心区域，临近天府广场及核心商圈。', NULL, 30.6500, 104.0633, 880.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(5, '西安大唐芙蓉园精品酒店', '西安', '雁塔区芙蓉南路100号', 4, '临近大唐芙蓉园景区，适合古都文化主题出行。', NULL, 34.2076, 109.0082, 680.00, 4.5, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(6, '三亚亚龙湾万豪度假酒店', '三亚', '亚龙湾国家旅游度假区', 5, '位于亚龙湾度假区，面向滨海休闲度假场景。', NULL, 18.2208, 109.6600, 2880.00, 4.9, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(7, '丽江古城铂尔曼大酒店', '丽江', '古城区象山路99号', 5, '临近丽江古城，面向古城休闲与雪山观光客群。', NULL, 26.8720, 100.2275, 1680.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(8, '杭州西湖喜来登大酒店', '杭州', '西湖区北山路9号', 5, '位于西湖周边，适合湖滨休闲及城市观光。', NULL, 30.2563, 120.1495, 1980.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(9, '重庆解放碑威斯汀酒店', '重庆', '渝中区中山三路36号', 5, '位于重庆中心城区，适合解放碑及两江夜景行程。', NULL, 29.5600, 106.5714, 1380.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(10, '北京王府井万豪酒店', '北京', '东城区王府井大街57号', 5, '位于王府井商圈，临近故宫、天安门等核心景点。', NULL, 39.9200, 116.4114, 1880.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(11, '上海静安香格里拉大酒店', '上海', '静安区静安寺路1218号', 5, '位于南京西路商圈，临近静安寺及商业办公区。', NULL, 31.2244, 121.4471, 1680.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(12, '厦门悦华酒店', '厦门', '湖里区乌石浦路2号', 4, '位于厦门岛内，适合商务与休闲出行。', NULL, 24.5020, 118.0936, 780.00, 4.5, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(13, '桂林香格里拉大酒店', '桂林', '象山区解放东路111号', 5, '临近漓江城市段，适合桂林山水观光行程。', NULL, 25.2877, 110.2978, 1180.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-19'),
(14, '青岛海景花园大酒店', '青岛', '市南区香港中路76号', 5, '位于青岛滨海城区，适合海滨度假及城市观光。', NULL, 36.0584, 120.3817, 1280.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-19');

INSERT IGNORE INTO `tm_hotel` (`id`, `name`, `city`, `address`, `star_rating`, `description`, `cover_img`, `lat`, `lng`, `avg_price`, `score`, `source_name`, `source_url`, `data_checked_date`) VALUES
(15, '全季酒店(成都太古里春熙路店)', '成都', '交通路8号中环广场2座', 4, '位于春熙路与太古里商圈周边，适合城市观光、购物和商务短住。', NULL, 30.661950, 104.078639, 520.00, 4.8, '携程酒店搜索', 'https://hotels.ctrip.com/hotels/detail/?hotelid=133457358', '2026-05-21'),
(16, '成都太古里春熙美居酒店', '成都', '暑袜北三街20号东楼', 4, '靠近成都太古里与春熙路，适合轻量 citywalk 和夜间餐饮行程。', NULL, 30.664968, 104.082064, 680.00, 4.8, '携程酒店搜索', 'https://hotels.ctrip.com/hotels/detail/?hotelid=21132716', '2026-05-21'),
(17, '成都瑞城名人酒店', '成都', '人民中路二段68号', 4, '临近文殊院和宽窄巷子，适合老城休闲与亲子出行。', NULL, 30.676451, 104.072363, 460.00, 4.7, '携程酒店搜索', 'https://hotels.ctrip.com/hotels/detail/?hotelid=470094', '2026-05-21'),
(18, '成都东大明宇豪雅饭店(春熙路太古里店)', '成都', '东大街紫东楼段39号', 5, '位于东大街商圈，适合高星商务、太古里购物和市区美食动线。', NULL, 30.652909, 104.097655, 980.00, 4.8, '携程酒店搜索', 'https://hotels.ctrip.com/hotels/detail/?hotelid=435688', '2026-05-21'),
(19, '南京金陵饭店', '南京', '新街口汉中路2号', 5, '南京新街口地标型酒店，适合城市中心商务、购物和博物馆游线。', NULL, 32.042447, 118.782824, 920.00, 4.8, '携程目的地/酒店联想', 'https://hotels.ctrip.com/hotels/detail/?hotelid=346283', '2026-05-21'),
(20, '苏州吴宫泛太平洋酒店', '苏州', '姑苏区新市路259号', 5, '临近盘门和姑苏古城片区，适合园林游览与江南度假。', NULL, 31.290418, 120.617053, 880.00, 4.7, '携程目的地/酒店联想', 'https://hotels.ctrip.com/hotels/detail/?hotelid=346290', '2026-05-21');

INSERT IGNORE INTO `tm_hotel` (`id`, `name`, `city`, `address`, `star_rating`, `description`, `cover_img`, `lat`, `lng`, `avg_price`, `score`, `source_name`, `source_url`, `data_checked_date`) VALUES
(21, '重庆解放碑来福士雅诗阁服务公寓', '重庆', '渝中区接圣街6号', 5, '位于朝天门和来福士商圈，适合家庭、长住和两江夜景行程。', '/images/real/hotels/chongqing-raffles-ascott.jpg', 29.566900, 106.588300, 1180.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(22, '南京夫子庙亚朵酒店', '南京', '秦淮区建康路附近', 4, '靠近夫子庙和秦淮河片区，适合夜游、家庭和周末短途。', '/images/real/hotels/nanjing-fuzimiao-atour.jpg', 32.023805, 118.791212, 560.00, 4.7, '携程目的地/酒店联想', 'https://hotels.ctrip.com/hotels/detail/?hotelid=8838971', '2026-05-21'),
(23, '苏州观前平江美居酒店', '苏州', '姑苏区观前平江片区', 4, '位于观前街和平江路周边，适合园林游、古城步行和美食探索。', '/images/real/hotels/suzhou-pingjiang-mercure.jpg', 31.308031, 120.635090, 620.00, 4.7, '携程目的地/酒店联想', 'https://hotels.ctrip.com/hotels/detail/?hotelid=64962190', '2026-05-21'),
(24, '厦门鼓浪屿海景度假酒店', '厦门', '思明区鼓浪屿内厝澳片区', 4, '面向鼓浪屿慢游和海岛度假场景，适合住岛看日落。', '/images/real/hotels/xiamen-gulangyu-seaview.jpg', 24.447900, 118.061600, 720.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(25, '长沙五一广场国金中心酒店', '长沙', '芙蓉区五一广场商圈', 4, '临近五一广场、IFS和黄兴路步行街，适合美食与夜生活行程。', 'https://ak-d.tripcdn.com/images/1mc0q12000mffam9bF93D.jpg', 28.193300, 112.976900, 520.00, 4.6, 'Trip.com 酒店图库/演示价格', 'https://sa.trip.com/hotels/changsha-hotel-detail-114935658/quan-ji-jiu-dian/photo.html', '2026-05-23'),
(26, '青岛八大关海景酒店', '青岛', '市南区八大关风景区附近', 4, '靠近八大关、第二海水浴场和栈桥片区，适合海滨城市度假。', '/images/real/hotels/qingdao-badaguan-seaview.jpg', 36.055300, 120.343600, 860.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-21');

INSERT INTO `tm_hotel` (`id`, `name`, `city`, `address`, `star_rating`, `description`, `cover_img`, `lat`, `lng`, `avg_price`, `score`, `source_name`, `source_url`, `data_checked_date`) VALUES
(31, '北京前门建国饭店', '北京', '西城区永安路175号', 4, '临近前门、大栅栏和天安门南侧，适合中轴线和老城游览。', '/images/real/hotels/qianmen-jianguo.webp', 39.889600, 116.393700, 760.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(32, '上海人民广场南京东路珍宝酒店', '上海', '黄浦区人民广场南京东路片区', 4, '靠近人民广场、南京路步行街和外滩，适合上海 citywalk。', '/images/real/hotels/shanghai-treasury.webp', 31.235800, 121.478900, 720.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(33, '杭州湖滨银泰亚朵酒店', '杭州', '上城区湖滨银泰商圈', 4, '临近西湖湖滨和地铁站，适合周末短住与亲子出行。', '/images/real/hotels/hangzhou-atour.webp', 30.257200, 120.165400, 680.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(34, '西安钟楼鼓楼美居酒店', '西安', '碑林区钟楼商圈', 4, '靠近钟楼、鼓楼和回民街，适合古城夜游与美食路线。', '/images/real/hotels/xian-mercure.webp', 34.261100, 108.942100, 520.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(35, '三亚海棠湾度假酒店', '三亚', '海棠区海棠湾国家海岸', 5, '面向亲子度假和免税购物场景，适合海棠湾慢旅行。', '/images/real/hotels/sanya-haitang-resort.webp', 18.307400, 109.736600, 1680.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-21'),
(36, '广州珠江新城雅致酒店', '广州', '天河区珠江新城商圈', 4, '临近花城广场、广州塔和珠江夜游动线，适合商务和城市观光。', '/images/real/hotels/guangzhou-elegant.webp', 23.120900, 113.324400, 690.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-21')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `city` = VALUES(`city`),
  `address` = VALUES(`address`),
  `star_rating` = VALUES(`star_rating`),
  `description` = VALUES(`description`),
  `cover_img` = VALUES(`cover_img`),
  `lat` = VALUES(`lat`),
  `lng` = VALUES(`lng`),
  `avg_price` = VALUES(`avg_price`),
  `score` = VALUES(`score`),
  `source_name` = VALUES(`source_name`),
  `source_url` = VALUES(`source_url`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_hotel` (`id`, `name`, `city`, `address`, `star_rating`, `description`, `cover_img`, `lat`, `lng`, `avg_price`, `score`, `source_name`, `source_url`, `data_checked_date`) VALUES
(41, '北京前门漫心府', '北京', '东城区前门东路与鲜鱼口街区附近', 4, '靠近前门、天安门和地铁站，适合第一次来北京的中轴线行程。', '/images/real/hotels/beijing-manxin.webp', 39.899200, 116.397800, 620.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(42, '北京望京凯悦精选酒店', '北京', '朝阳区望京商圈', 4, '临近望京商业区和地铁换乘站，适合商务与亲子短住。', '/images/real/hotels/beijing-hyatt-wangjing.jpg', 39.990600, 116.480700, 720.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(43, '上海外滩南京东路亚朵S酒店', '上海', '黄浦区南京东路步行街附近', 4, '步行可达外滩和人民广场，适合城市漫步和夜景行程。', '/images/real/hotels/shanghai-bund-atour.webp', 31.239000, 121.484500, 780.00, 4.8, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(44, '上海徐家汇衡山路花园酒店', '上海', '徐汇区衡山路街区', 4, '靠近衡山路、徐家汇和武康路，适合法租界 citywalk。', '/images/real/hotels/shanghai-hengshan-garden.webp', 31.201600, 121.443800, 690.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(45, '成都宽窄巷子桔子水晶酒店', '成都', '青羊区宽窄巷子商圈', 4, '适合宽窄巷子、人民公园和市区美食路线，地铁出行方便。', '/images/real/hotels/chengdu-orange-crystal.jpg', 30.669400, 104.056900, 520.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(46, '成都东站希尔顿欢朋酒店', '成都', '成华区成都东站附近', 4, '靠近成都东站，适合高铁中转和川西出发前后住宿。', '/images/real/hotels/chengdu-east-hampton.jpg', 30.629300, 104.142600, 460.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(47, '西安钟楼回民街亚朵酒店', '西安', '莲湖区钟楼回民街片区', 4, '临近钟楼、鼓楼和回民街，夜游与美食路线集中。', '/images/real/hotels/xian-atour.webp', 34.264600, 108.943700, 480.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(48, '广州珠江新城希尔顿欢朋酒店', '广州', '天河区珠江新城核心区', 4, '靠近花城广场、广东省博物馆和广州塔夜景动线。', '/images/real/hotels/guangzhou-hampton.webp', 23.123400, 113.324800, 620.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(49, '厦门中山路海景美居酒店', '厦门', '思明区中山路与鹭江道附近', 4, '靠近八市、中山路和鼓浪屿码头，适合厦门三日慢游。', '/images/real/hotels/xiamen-mercure-seaview.jpg', 24.455600, 118.080500, 580.00, 4.6, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(50, '青岛五四广场海景亚朵酒店', '青岛', '市南区五四广场商圈', 4, '靠近奥帆中心、五四广场和海边步道，适合看海和城市夜景。', '/images/real/hotels/qingdao-atour-seaview.jpg', 36.064900, 120.384800, 650.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(51, '重庆解放碑洪崖洞漫心酒店', '重庆', '渝中区解放碑步行街附近', 4, '步行可达解放碑、八一好吃街和洪崖洞夜景。', '/images/real/hotels/chongqing-hongyadong-manxin.jpg', 29.560500, 106.581900, 560.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25'),
(52, '杭州西湖湖滨君亭酒店', '杭州', '上城区湖滨银泰商圈', 4, '临近西湖湖滨、龙翔桥地铁站和银泰商圈，适合周末短途。', '/images/real/hotels/hangzhou-junting-hubin.jpg', 30.257900, 120.165900, 620.00, 4.7, '公开酒店信息/演示价格', NULL, '2026-05-25')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `city` = VALUES(`city`),
  `address` = VALUES(`address`),
  `star_rating` = VALUES(`star_rating`),
  `description` = VALUES(`description`),
  `cover_img` = VALUES(`cover_img`),
  `lat` = VALUES(`lat`),
  `lng` = VALUES(`lng`),
  `avg_price` = VALUES(`avg_price`),
  `score` = VALUES(`score`),
  `source_name` = VALUES(`source_name`),
  `source_url` = VALUES(`source_url`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT IGNORE INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`) VALUES
(1, '豪华大床房', '1.8m大床', 45, 1280.00, 20, 15, 'WiFi,空调,浴缸,迷你吧,城市景观'),
(1, '豪华双床房', '2×1.2m双床', 45, 1380.00, 15, 10, 'WiFi,空调,淋浴,迷你吧,城市景观'),
(1, '豪华套房', '2m大床', 90, 2980.00, 5, 3, 'WiFi,空调,浴缸,客厅,城市景观,管家服务'),
(2, '外滩景观大床房', '2m大床', 55, 2180.00, 25, 8, 'WiFi,空调,浴缸,外滩景观,迷你吧'),
(2, '标准双床房', '2×1.2m双床', 45, 1880.00, 20, 12, 'WiFi,空调,淋浴,城市景观'),
(2, '豪华套房', '2m大床', 120, 4580.00, 3, 2, 'WiFi,空调,浴缸,外滩全景,管家,客厅'),
(3, '江景标准间', '1.5m双床', 38, 980.00, 30, 20, 'WiFi,空调,淋浴,江景'),
(3, '豪华大床房', '1.8m大床', 42, 1180.00, 20, 14, 'WiFi,空调,浴缸,园景'),
(4, '商务大床房', '1.8m大床', 40, 780.00, 30, 22, 'WiFi,空调,淋浴,城市景观'),
(4, '豪华双床房', '2×1.2m双床', 42, 880.00, 20, 16, 'WiFi,空调,淋浴,城市景观'),
(5, '仿唐主题大床房', '1.8m大床', 38, 580.00, 25, 18, 'WiFi,空调,淋浴,唐风装饰'),
(5, '唐韵套房', '2m大床', 75, 1280.00, 5, 4, 'WiFi,空调,浴缸,客厅,院景'),
(6, '海景大床房', '2m大床', 60, 2580.00, 30, 8, 'WiFi,空调,私人阳台,海景,迷你吧'),
(6, '豪华套房', '2m大床', 120, 4980.00, 5, 2, 'WiFi,空调,私人泳池,直达沙滩,管家'),
(7, '雪山景观大床房', '1.8m大床', 45, 1480.00, 20, 12, 'WiFi,空调,浴缸,玉龙雪山景观'),
(8, '湖景大床房', '2m大床', 55, 1780.00, 25, 6, 'WiFi,空调,浴缸,西湖全景,迷你吧'),
(8, '豪华套房', '2m大床', 110, 3880.00, 3, 1, 'WiFi,空调,客厅,西湖全景,管家服务');

INSERT INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`)
SELECT `hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`
FROM (
  SELECT 9 AS `hotel_id`, '解放碑城景大床房' AS `room_type`, '1.8m大床' AS `bed_type`, 42 AS `area`, 1180.00 AS `price`, 22 AS `total_rooms`, 13 AS `available_rooms`, 'WiFi,空调,浴缸,城市景观,迷你吧' AS `facilities`
  UNION ALL SELECT 9, '两江夜景套房', '2m大床', 72, 1980.00, 8, 4, 'WiFi,浴缸,客厅,两江夜景,行政礼遇'
  UNION ALL SELECT 10, '王府井豪华大床房', '1.8m大床', 40, 1580.00, 24, 15, 'WiFi,空调,浴缸,近故宫,城市景观'
  UNION ALL SELECT 10, '亲子家庭房', '1.8m+1.2m床', 52, 1980.00, 10, 6, 'WiFi,亲子用品,早餐,近王府井'
  UNION ALL SELECT 11, '静安寺景观大床房', '1.8m大床', 45, 1480.00, 24, 14, 'WiFi,空调,浴缸,静安寺景观,迷你吧'
  UNION ALL SELECT 11, '行政双床房', '2×1.2m双床', 50, 1880.00, 14, 8, 'WiFi,行政楼层,浴缸,早餐,城市景观'
  UNION ALL SELECT 12, '悦华商务大床房', '1.8m大床', 36, 680.00, 26, 18, 'WiFi,空调,淋浴,办公桌,近机场'
  UNION ALL SELECT 12, '厦门亲子双床房', '1.5m+1.2m床', 42, 820.00, 16, 10, 'WiFi,亲子用品,早餐,停车,园景'
  UNION ALL SELECT 12, '悦华行政套房', '2m大床', 68, 1280.00, 6, 3, 'WiFi,浴缸,客厅,行政礼遇,迷你吧'
  UNION ALL SELECT 13, '漓江景观大床房', '1.8m大床', 46, 980.00, 22, 12, 'WiFi,空调,浴缸,漓江景观,早餐'
  UNION ALL SELECT 13, '桂林家庭套房', '1.8m+1.2m床', 62, 1380.00, 8, 5, 'WiFi,亲子用品,客厅,江景,停车'
  UNION ALL SELECT 14, '青岛海景大床房', '1.8m大床', 42, 1080.00, 20, 11, 'WiFi,空调,浴缸,海景,近海滩'
  UNION ALL SELECT 14, '海景亲子双床房', '1.5m+1.2m床', 50, 1280.00, 12, 7, 'WiFi,亲子用品,海景,早餐,停车'
) AS new_rooms
WHERE NOT EXISTS (
  SELECT 1 FROM `tm_hotel_room` r
  WHERE r.`hotel_id` = new_rooms.`hotel_id`
    AND r.`room_type` = new_rooms.`room_type`
);

INSERT IGNORE INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`) VALUES
(15, '高级大床房', '1.8m大床', 28, 458.00, 30, 21, 'WiFi,空调,淋浴,办公桌,近地铁'),
(15, '商务双床房', '2×1.2m双床', 30, 518.00, 20, 14, 'WiFi,空调,淋浴,城市景观'),
(16, '嘉宾大床房', '1.8m大床', 32, 628.00, 28, 17, 'WiFi,空调,淋浴,迷你吧,近太古里'),
(16, '家庭双床房', '1.5m+1.2m床', 38, 728.00, 12, 8, 'WiFi,空调,亲子用品,城市景观'),
(17, '文殊院舒适大床房', '1.8m大床', 30, 398.00, 25, 18, 'WiFi,空调,淋浴,早餐'),
(18, '豪华城景大床房', '2m大床', 48, 898.00, 22, 12, 'WiFi,浴缸,迷你吧,城市景观,健身房'),
(18, '行政套房', '2m大床', 82, 1680.00, 6, 3, 'WiFi,浴缸,客厅,行政礼遇'),
(19, '金陵经典大床房', '1.8m大床', 36, 820.00, 24, 15, 'WiFi,空调,浴缸,新街口景观'),
(19, '行政双床房', '2×1.2m双床', 42, 1080.00, 16, 9, 'WiFi,浴缸,行政楼层,早餐'),
(20, '姑苏园景大床房', '1.8m大床', 40, 760.00, 20, 13, 'WiFi,园景,浴缸,近盘门'),
(20, '亲子家庭房', '1.8m+1.2m床', 50, 980.00, 10, 6, 'WiFi,亲子用品,园景,停车');

INSERT IGNORE INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`) VALUES
(21, '两江景观大床房', '1.8m大床', 45, 980.00, 18, 9, 'WiFi,江景,洗衣机,厨房,浴缸'),
(21, '家庭双卧套房', '2间卧室', 88, 1680.00, 8, 4, 'WiFi,江景,厨房,客厅,洗衣机'),
(22, '秦淮舒适大床房', '1.8m大床', 30, 498.00, 26, 18, 'WiFi,空调,淋浴,近夫子庙'),
(22, '秦淮亲子房', '1.8m+1.2m床', 38, 658.00, 12, 7, 'WiFi,亲子用品,早餐,近地铁'),
(23, '平江路大床房', '1.8m大床', 32, 568.00, 22, 13, 'WiFi,空调,淋浴,近园林'),
(23, '观前双床房', '2×1.2m双床', 34, 628.00, 18, 10, 'WiFi,空调,早餐,步行街'),
(24, '海岛庭院大床房', '1.8m大床', 30, 680.00, 16, 8, 'WiFi,庭院,近码头,早餐'),
(24, '鼓浪屿海景房', '1.8m大床', 36, 920.00, 10, 5, 'WiFi,海景,阳台,早餐'),
(25, '五一广场城景房', '1.8m大床', 32, 468.00, 28, 20, 'WiFi,空调,城市景观,近地铁'),
(25, '黄兴路双床房', '2×1.2m双床', 35, 528.00, 20, 12, 'WiFi,空调,淋浴,步行街'),
(26, '八大关海景大床房', '1.8m大床', 38, 780.00, 18, 9, 'WiFi,海景,浴缸,近海滩'),
(26, '亲子海景套房', '1.8m+1.2m床', 55, 1180.00, 8, 3, 'WiFi,亲子用品,海景,客厅');

INSERT IGNORE INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`) VALUES
(31, '前门舒适大床房', '1.8m大床', 30, 658.00, 24, 16, 'WiFi,空调,淋浴,近地铁'),
(31, '中轴线家庭房', '1.8m+1.2m床', 42, 858.00, 12, 7, 'WiFi,亲子用品,早餐,近前门'),
(32, '南京路景观大床房', '1.8m大床', 32, 698.00, 26, 17, 'WiFi,空调,城市景观,近外滩'),
(32, '人民广场双床房', '2×1.2m双床', 34, 758.00, 18, 11, 'WiFi,空调,淋浴,近地铁'),
(33, '湖滨雅致大床房', '1.8m大床', 31, 628.00, 22, 14, 'WiFi,空调,早餐,近西湖'),
(33, '西湖亲子房', '1.8m+1.2m床', 40, 828.00, 10, 5, 'WiFi,亲子用品,近湖滨,早餐'),
(34, '钟楼城景大床房', '1.8m大床', 30, 468.00, 24, 18, 'WiFi,空调,城市景观,近地铁'),
(34, '鼓楼家庭房', '1.8m+1.2m床', 38, 628.00, 12, 8, 'WiFi,亲子用品,近回民街'),
(35, '海棠湾园景房', '2m大床', 55, 1380.00, 24, 12, 'WiFi,阳台,泳池,亲子活动'),
(35, '海景亲子套房', '2m大床+儿童床', 82, 2380.00, 8, 3, 'WiFi,海景,浴缸,亲子用品,行政礼遇'),
(36, '珠江新城商务大床房', '1.8m大床', 34, 620.00, 26, 15, 'WiFi,办公桌,城市景观,近地铁'),
(36, '广州塔景观房', '1.8m大床', 42, 860.00, 12, 6, 'WiFi,塔景,浴缸,迷你吧');

INSERT IGNORE INTO `tm_hotel_room` (`hotel_id`, `room_type`, `bed_type`, `area`, `price`, `total_rooms`, `available_rooms`, `facilities`) VALUES
(41, '前门雅致大床房', '1.8m大床', 30, 598.00, 22, 14, 'WiFi,空调,近地铁,行李寄存'),
(41, '老城家庭房', '1.8m+1.2m床', 38, 798.00, 10, 6, 'WiFi,亲子用品,早餐,近前门'),
(42, '望京商务大床房', '1.8m大床', 32, 688.00, 24, 16, 'WiFi,办公桌,健身房,洗衣房'),
(42, '精选双床房', '2×1.2m双床', 35, 728.00, 18, 10, 'WiFi,早餐,近商圈,停车'),
(43, '南京路景观大床房', '1.8m大床', 31, 758.00, 26, 18, 'WiFi,城市景观,近外滩,洗衣房'),
(43, '外滩亲子双床房', '1.5m+1.2m床', 40, 958.00, 12, 7, 'WiFi,亲子用品,早餐,近地铁'),
(44, '衡山路花园大床房', '1.8m大床', 30, 668.00, 24, 15, 'WiFi,咖啡角,近武康路,安静街区'),
(44, '徐家汇双床房', '2×1.2m双床', 34, 728.00, 16, 9, 'WiFi,办公桌,近地铁,早餐'),
(45, '宽窄巷子大床房', '1.8m大床', 30, 498.00, 28, 17, 'WiFi,空调,近人民公园,洗衣房'),
(45, '成都美食双床房', '2×1.2m双床', 34, 558.00, 18, 12, 'WiFi,早餐,近地铁,行李寄存'),
(46, '东站中转大床房', '1.8m大床', 28, 428.00, 30, 20, 'WiFi,近高铁站,早餐,接驳咨询'),
(46, '东站商务双床房', '2×1.2m双床', 32, 488.00, 18, 11, 'WiFi,办公桌,洗衣房,近地铁'),
(47, '钟楼夜景大床房', '1.8m大床', 30, 458.00, 26, 16, 'WiFi,城市景观,近回民街,早餐'),
(47, '古城家庭房', '1.8m+1.2m床', 40, 638.00, 12, 8, 'WiFi,亲子用品,近地铁,行李寄存'),
(48, '珠江新城商务房', '1.8m大床', 32, 598.00, 28, 18, 'WiFi,办公桌,健身房,近花城广场'),
(48, '广州塔景观双床房', '2×1.2m双床', 38, 768.00, 14, 7, 'WiFi,塔景,早餐,近地铁'),
(49, '中山路舒适大床房', '1.8m大床', 29, 528.00, 24, 15, 'WiFi,近八市,行李寄存,洗衣房'),
(49, '鹭江海景双床房', '2×1.2m双床', 36, 698.00, 12, 6, 'WiFi,海景,近码头,早餐'),
(50, '五四广场海景房', '1.8m大床', 34, 628.00, 24, 13, 'WiFi,海景,近奥帆中心,早餐'),
(50, '市南家庭双床房', '2×1.35m双床', 42, 788.00, 10, 5, 'WiFi,亲子用品,海边步道,行李寄存'),
(51, '解放碑城景大床房', '1.8m大床', 30, 528.00, 26, 17, 'WiFi,近洪崖洞,洗衣房,早餐'),
(51, '山城夜景双床房', '2×1.2m双床', 36, 638.00, 16, 9, 'WiFi,夜景,近地铁,行李寄存'),
(52, '湖滨雅致大床房', '1.8m大床', 30, 588.00, 24, 15, 'WiFi,近西湖,早餐,洗衣房'),
(52, '西湖亲子双床房', '2×1.2m双床', 39, 758.00, 12, 7, 'WiFi,亲子用品,近湖滨,行李寄存');

INSERT INTO `tm_attraction` (`id`, `name`, `city`, `address`, `description`, `cover_img`, `adult_price`, `child_price`, `total_tickets`, `available_tickets`, `open_time`, `lat`, `lng`, `official_url`, `source_name`, `data_checked_date`) VALUES
(1, '故宫博物院', '北京', '东城区景山前街4号', '明清两代皇家宫殿，世界文化遗产，馆藏体系覆盖古代宫廷建筑、书画、器物等。', NULL, 60.00, 0.00, 1000, 456, '08:30-17:00（旺季，周一闭馆，法定节假日除外）', 39.916345, 116.397155, 'https://www.dpm.org.cn/Visit.html', '故宫博物院官网', '2026-05-19'),
(2, '颐和园', '北京', '海淀区新建宫门路19号', '以昆明湖、万寿山为主体的大型皇家园林，1998年列入世界遗产名录。', NULL, 30.00, 0.00, 2000, 1234, '06:00-20:00（旺季，停止入园19:00）', 39.999946, 116.275481, 'https://www.summerpalace.net.cn/visit.html', '颐和园官网', '2026-05-19'),
(3, '外滩', '上海', '黄浦区中山东一路', '上海近代城市景观代表区域，沿黄浦江分布多座历史建筑，是城市公共开放空间。', NULL, 0.00, 0.00, 9999, 9999, '全天开放', 31.239706, 121.490317, 'https://www.shhuangpu.gov.cn/', '上海市黄浦区人民政府', '2026-05-19'),
(4, '西湖', '杭州', '西湖区龙井路1号', '杭州西湖文化景观为世界文化遗产，核心湖区与沿湖开放空间面向公众开放。', NULL, 0.00, 0.00, 9999, 9999, '全天开放（部分收费景点另行开放）', 30.242703, 120.150269, 'https://westlake.hangzhou.gov.cn/', '杭州西湖风景名胜区管委会', '2026-05-19'),
(5, '张家界国家森林公园', '张家界', '武陵源区国家森林公园内', '中国第一个国家森林公园，武陵源世界自然遗产核心景区之一，以石英砂岩峰林地貌著称。', NULL, 227.00, 113.00, 500, 234, '07:30-18:00（以景区当日公告为准）', 29.327001, 110.475704, 'https://wly.hunan.gov.cn/', '湖南省文化和旅游厅/武陵源景区公开信息', '2026-05-19'),
(6, '秦始皇帝陵博物院', '西安', '临潼区秦陵北路', '以秦始皇兵马俑坑和秦始皇陵相关遗址为核心的遗址类博物馆。', NULL, 120.00, 0.00, 800, 356, '08:30-18:30（旺季，停止检票17:00）', 34.384018, 109.278491, 'https://www.bmy.com.cn/', '秦始皇帝陵博物院官网', '2026-05-19'),
(7, '九寨沟风景名胜区', '阿坝', '阿坝藏族羌族自治州九寨沟县漳扎镇', '以高山湖泊、瀑布群、彩林和雪峰景观闻名的世界自然遗产。', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/1_jiuzhaigou_valley_wu_hua_hai_2011b.jpg', 190.00, 95.00, 1000, 445, '07:30-17:00（旺季，具体以景区公告为准）', 33.260772, 103.918599, 'https://www.jiuzhai.com/intelligent-service/tickets', '九寨沟风景名胜区官网', '2026-05-19'),
(8, '黄山风景区', '黄山', '黄山市黄山区汤口镇', '世界文化与自然双重遗产，以奇松、怪石、云海、温泉等景观著称。', NULL, 190.00, 95.00, 1500, 678, '06:00-17:30（旺季，具体以景区公告为准）', 30.130130, 118.168498, 'https://hsgwh.huangshan.gov.cn/', '黄山风景区管委会', '2026-05-19'),
(9, '漓江风景名胜区', '桂林', '桂林市灵川县至阳朔县漓江沿线', '桂林山水代表性景区，游船线路以漓江喀斯特峰林、江湾和田园景观为核心。', NULL, 210.00, 105.00, 600, 289, '08:00-12:00（游船班次以当日公告为准）', 25.166667, 110.416667, 'https://wglj.guilin.gov.cn/', '桂林市文化广电和旅游局', '2026-05-19'),
(10, '天坛公园', '北京', '东城区天坛东里甲1号', '明清两代皇帝祭天祈谷场所，是北京中轴线南段的重要世界文化遗产。', NULL, 34.00, 17.00, 2000, 1280, '06:00-22:00（景点院落开放时间另行公告）', 39.882200, 116.406600, 'http://www.tiantanpark.com/', '天坛公园官网', '2026-05-19'),
(11, '八达岭长城', '北京', '延庆区G6京藏高速58号出口', '明长城重要关隘，保存状况较好，是北京长城游览代表景区。', NULL, 40.00, 20.00, 2500, 1600, '06:30-16:30（以景区公告为准）', 40.358100, 116.020300, 'https://www.badaling.cn/', '八达岭长城景区官网', '2026-05-19'),
(12, '东方明珠广播电视塔', '上海', '浦东新区世纪大道1号', '上海陆家嘴地标建筑，集城市观光、展览和餐饮功能于一体。', NULL, 199.00, 99.00, 1800, 920, '09:00-21:00（以景区公告为准）', 31.239700, 121.499800, 'https://www.orientalpearltower.com/', '东方明珠官网', '2026-05-19'),
(13, '豫园', '上海', '黄浦区福佑路168号', '江南古典园林代表之一，周边连接豫园商城和城隍庙历史文化街区。', NULL, 40.00, 20.00, 1200, 760, '09:00-16:30（以景区公告为准）', 31.227200, 121.492100, 'https://www.yuyuantm.com.cn/', '豫园商城公开信息', '2026-05-19'),
(14, '上海迪士尼乐园', '上海', '浦东新区川沙新镇黄赵路310号', '大型主题乐园，包含主题园区、演艺、巡游和烟花等游乐体验。', NULL, 475.00, 356.00, 3000, 1780, '08:30-21:30（以乐园日历为准）', 31.143400, 121.657900, 'https://www.shanghaidisneyresort.com/', '上海迪士尼度假区官网', '2026-05-19'),
(15, '成都大熊猫繁育研究基地', '成都', '成华区熊猫大道1375号', '以大熊猫保护、繁育、科研和公众教育为核心的生态型景区。', NULL, 55.00, 27.00, 2000, 1188, '07:30-18:00（以景区公告为准）', 30.735500, 104.145600, 'https://www.panda.org.cn/', '成都大熊猫繁育研究基地官网', '2026-05-19'),
(16, '都江堰景区', '成都', '都江堰市公园路', '世界文化遗产，古代水利工程代表，与青城山共同构成重要旅游目的地。', NULL, 80.00, 40.00, 1800, 960, '08:00-18:00（以景区公告为准）', 31.001700, 103.605500, 'https://www.djy517.com/', '都江堰青城山景区官网', '2026-05-19'),
(17, '蜈支洲岛', '三亚', '海棠区林旺镇后海村', '三亚近海海岛景区，以海水能见度、潜水和滨海休闲项目闻名。', NULL, 136.00, 68.00, 1500, 820, '08:00-18:30（航班以天气和公告为准）', 18.312600, 109.757400, 'https://www.wuzhizhou.com/', '蜈支洲岛旅游区官网', '2026-05-19'),
(18, '天涯海角游览区', '三亚', '天涯区天涯镇马岭山麓', '海南代表性滨海文化景区，以海滨礁石景观和“天涯”“海角”题刻闻名。', NULL, 68.00, 34.00, 1600, 900, '08:00-18:00（以景区公告为准）', 18.296000, 109.344000, 'https://www.aitianya.cn/', '天涯海角游览区官网', '2026-05-19'),
(19, '丽江古城', '丽江', '古城区大研古城', '世界文化遗产，以纳西族传统街巷、水系和民居建筑景观著称。', NULL, 0.00, 0.00, 9999, 9999, '全天开放（部分院落另行开放）', 26.872200, 100.233000, 'https://www.ljgucheng.com/', '丽江古城保护管理局公开信息', '2026-05-19'),
(20, '亚龙湾国家旅游度假区', '三亚', '吉阳区亚龙湾国家旅游度假区', '三亚重要滨海度假区，以海湾、沙滩和度假酒店群为主要吸引物。', NULL, 0.00, 0.00, 9999, 9999, '全天开放（海滩及项目以现场公告为准）', 18.229500, 109.637000, 'https://lwj.sanya.gov.cn/', '三亚市旅游和文化广电体育局', '2026-05-19'),
(21, '鼓浪屿', '厦门', '思明区鼓浪屿', '世界文化遗产，融合海岛街巷、近代建筑和音乐文化景观。', NULL, 0.00, 0.00, 9999, 9999, '全天开放（上岛船班及收费景点另行公告）', 24.447700, 118.061900, 'https://gly.xm.gov.cn/', '鼓浪屿管委会公开信息', '2026-05-19'),
(22, '中山陵', '南京', '玄武区石象路7号', '孙中山先生陵寝所在地，位于钟山风景名胜区内，是南京重要历史文化地标。', NULL, 0.00, 0.00, 3000, 2100, '08:30-17:00（周一部分区域闭馆，节假日除外）', 32.064300, 118.848600, 'https://zschina.nanjing.gov.cn/', '南京钟山风景区官网', '2026-05-19'),
(23, '拙政园', '苏州', '姑苏区东北街178号', '苏州古典园林代表，世界文化遗产，以水景、亭台和园林空间布局著称。', NULL, 80.00, 40.00, 1400, 780, '07:30-17:30（以景区公告为准）', 31.324300, 120.629700, 'https://www.szzzy.cn/', '拙政园官网', '2026-05-19'),
(24, '洪崖洞民俗风貌区', '重庆', '渝中区嘉陵江滨江路88号', '重庆山城夜景代表地，以吊脚楼风貌、滨江夜景和城市商业空间闻名。', NULL, 0.00, 0.00, 9999, 9999, '全天开放（商户营业时间不一）', 29.562800, 106.584000, 'https://whlyw.cq.gov.cn/', '重庆市文化和旅游发展委员会', '2026-05-19'),
(25, '龙脊梯田', '桂林', '龙胜各族自治县和平乡', '桂林北部山地梯田景观，包含平安寨、金坑大寨等观景区域。', NULL, 80.00, 40.00, 1000, 520, '08:00-17:30（以景区公告为准）', 25.764000, 110.123000, 'https://wglj.guilin.gov.cn/', '桂林市文化广电和旅游局', '2026-05-19'),
(26, '象鼻山景区', '桂林', '象山区滨江路1号', '桂林城市山水代表景观，山体形似象鼻伸入漓江，是桂林标志性景点。', NULL, 0.00, 0.00, 1800, 1260, '07:00-18:00（以景区公告为准）', 25.273900, 110.296700, 'https://wglj.guilin.gov.cn/', '桂林市文化广电和旅游局', '2026-05-19'),
(27, '天门山国家森林公园', '张家界', '永定区大庸路', '张家界城市近郊山岳型景区，以天门洞、玻璃栈道和索道体验闻名。', NULL, 278.00, 139.00, 1200, 660, '08:00-18:00（索道及线路以景区公告为准）', 29.044600, 110.482400, 'https://wly.hunan.gov.cn/', '湖南省文化和旅游厅/天门山公开信息', '2026-05-19'),
(28, '宏村', '黄山', '黟县宏村镇', '皖南古村落代表，世界文化遗产，以月沼、水圳和徽派民居格局著称。', NULL, 104.00, 52.00, 1200, 720, '07:30-17:30（以景区公告为准）', 30.004900, 117.987500, 'https://ct.ah.gov.cn/', '安徽省文化和旅游厅公开信息', '2026-05-19')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `city` = VALUES(`city`),
  `address` = VALUES(`address`),
  `description` = VALUES(`description`),
  `cover_img` = VALUES(`cover_img`),
  `adult_price` = VALUES(`adult_price`),
  `child_price` = VALUES(`child_price`),
  `open_time` = VALUES(`open_time`),
  `lat` = VALUES(`lat`),
  `lng` = VALUES(`lng`),
  `official_url` = VALUES(`official_url`),
  `source_name` = VALUES(`source_name`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_attraction` (`id`, `name`, `city`, `address`, `description`, `cover_img`, `adult_price`, `child_price`, `total_tickets`, `available_tickets`, `open_time`, `lat`, `lng`, `official_url`, `source_name`, `data_checked_date`) VALUES
(29, '夫子庙秦淮风光带', '南京', '秦淮区夫子庙贡院街', '南京代表性历史文化街区，夜游秦淮河、江南贡院和夫子庙商圈集中分布。', 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Night_View_of_Nanjing_Fuzimiao.jpg', 0.00, 0.00, 9999, 9999, '全天开放（游船和场馆另行开放）', 32.020600, 118.788900, 'https://wlj.nanjing.gov.cn/', '南京市文化和旅游局公开信息', '2026-05-21'),
(30, '平江路历史街区', '苏州', '姑苏区平江路', '苏州古城代表性历史街区，保留河街并行格局，适合步行和夜游。', 'https://upload.wikimedia.org/wikipedia/commons/8/88/Pingjiang_Road%2C_Suzhou.jpg', 0.00, 0.00, 9999, 9999, '全天开放（商户营业时间不一）', 31.314700, 120.633700, 'https://wglj.suzhou.gov.cn/', '苏州市文化广电和旅游局公开信息', '2026-05-21'),
(31, '沙坡尾艺术西区', '厦门', '思明区沙坡尾', '厦门老港口与城市更新街区，集合咖啡、展览、市集和海边步行体验。', 'https://upload.wikimedia.org/wikipedia/commons/b/b6/Gulangyu_Island_from_Zhongshan_Road%2C_Xiamen.jpg', 0.00, 0.00, 9999, 9999, '全天开放（商户营业时间不一）', 24.437200, 118.091400, 'https://wlj.xm.gov.cn/', '厦门市文化和旅游局公开信息', '2026-05-21'),
(32, '橘子洲景区', '长沙', '岳麓区橘子洲头', '湘江江心洲景区，是长沙城市观光和夜游烟花活动的重要地标。', 'https://upload.wikimedia.org/wikipedia/commons/7/7f/Orange_Isle%2C_Changsha.jpg', 0.00, 0.00, 9999, 9999, '07:00-22:00（以景区公告为准）', 28.181900, 112.959500, 'https://wlj.changsha.gov.cn/', '长沙市文化旅游广电局公开信息', '2026-05-21'),
(33, '八大关风景区', '青岛', '市南区汇泉角东北部', '青岛海滨历史建筑街区，适合城市漫步、建筑观赏和海边拍照。', 'https://upload.wikimedia.org/wikipedia/commons/7/71/Badaguan%2C_Qingdao.jpg', 0.00, 0.00, 9999, 9999, '全天开放（部分建筑另行开放）', 36.050200, 120.347800, 'https://whlyj.qingdao.gov.cn/', '青岛市文化和旅游局公开信息', '2026-05-21')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `city` = VALUES(`city`),
  `address` = VALUES(`address`),
  `description` = VALUES(`description`),
  `cover_img` = VALUES(`cover_img`),
  `adult_price` = VALUES(`adult_price`),
  `child_price` = VALUES(`child_price`),
  `open_time` = VALUES(`open_time`),
  `lat` = VALUES(`lat`),
  `lng` = VALUES(`lng`),
  `official_url` = VALUES(`official_url`),
  `source_name` = VALUES(`source_name`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT INTO `tm_attraction` (`id`, `name`, `city`, `address`, `description`, `cover_img`, `adult_price`, `child_price`, `total_tickets`, `available_tickets`, `open_time`, `lat`, `lng`, `official_url`, `source_name`, `data_checked_date`) VALUES
(29, '黄鹤楼', '武汉', '武昌区蛇山峰岭之上',
  '中国历史名楼之一，矗立于武汉蛇山，登楼可俯瞰长江与武汉三镇城市风貌，是湖北省标志性文化地标。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/HuangHe_Tower.jpg',
  70.00, 35.00, 2000, 1456, '08:00-18:00（旺季，停止入场17:30）',
  30.5447, 114.3029, 'https://www.yhl.com.cn/', '黄鹤楼公园官网', '2026-05-19'),

(30, '布达拉宫', '拉萨', '城关区布达拉宫广场',
  '矗立于拉萨红山之上，历代达赖喇嘛冬宫，世界文化遗产，藏传佛教圣地。每日严格限流，须至少提前3天预约。',
  '/images/real/attractions/potala.jpg',
  200.00, 0.00, 2300, 342, '09:00-15:00（每日限流，须提前预约）',
  29.6578, 91.1174, 'https://www.potalapalace.cn/', '布达拉宫管理处官网', '2026-05-19'),

(31, '纳木错', '拉萨', '当雄县纳木错湖区',
  '藏语意为"天湖"，海拔4718米，西藏最大湖泊，以圣湖美景和雪山倒影闻名。高海拔须注意高原反应。',
  '/images/real/attractions/tianshan-tianchi.jpg',
  120.00, 60.00, 1000, 780, '08:00-18:00（以景区公告为准）',
  30.7367, 90.5227, NULL, '那曲市文化和旅游局公开信息', '2026-05-19'),

(32, '莫高窟', '敦煌', '甘肃省敦煌市鸣沙山东麓',
  '俗称千佛洞，世界上现存规模最大、保存最完好的佛教艺术宝库，世界文化遗产。须提前网络预约，日票额有限。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Mogao_Caves%2C_cave_159_musicians.jpg/960px-Mogao_Caves%2C_cave_159_musicians.jpg',
  238.00, 119.00, 6000, 2130, '08:00-17:00（A类票额，参观时段固定，须提前预约）',
  40.0361, 94.8086, 'https://www.dha.ac.cn/', '敦煌研究院官网', '2026-05-19'),

(33, '乐山大佛', '乐山', '四川省乐山市凌云山',
  '世界最高石刻弥勒佛坐像，依山而凿，通高71米，与乌尤寺、凌云寺共同构成景区，世界文化与自然双遗产。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Leshan_Giant_Buddha%2C_20161102.jpg/960px-Leshan_Giant_Buddha%2C_20161102.jpg',
  120.00, 60.00, 2000, 1560, '07:30-18:30（旺季）',
  29.5458, 103.7716, 'https://www.leshandafo.com/', '乐山大佛景区官网', '2026-05-19'),

(34, '峨眉山', '乐山', '四川省峨眉山市',
  '佛教四大名山之一，以金顶云海、雷洞坪等景观闻名，与乐山大佛共同列入世界文化与自然双遗产，海拔3079米。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jinding.jpg/960px-Jinding.jpg',
  160.00, 80.00, 3000, 1870, '06:00-18:00（缆车另计，以景区公告为准）',
  29.6159, 103.3436, 'https://www.emeishan.com/', '峨眉山景区官网', '2026-05-19'),

(35, '泰山', '泰安', '山东省泰安市泰山区',
  '五岳之首，世界自然与文化双遗产，古代帝王封禅之地，以日出云海和南天门石阶著称。可徒步或乘缆车。',
  '/images/real/attractions/taishan.jpg',
  125.00, 62.00, 5000, 3400, '全天开放（缆车运营时间以公告为准）',
  36.2538, 117.1082, 'https://www.taishan.com/', '泰山景区官网', '2026-05-19'),

(36, '天山天池', '乌鲁木齐', '新疆昌吉回族自治州阜康市',
  '天山博格达峰下高山冰碛湖，海拔1910米，以雪山倒映和天山云杉林著称，国家5A级风景区。',
  '/images/real/attractions/tianshan-tianchi.jpg',
  100.00, 50.00, 2000, 1380, '08:00-20:00（旺季，以景区公告为准）',
  43.8851, 88.1206, NULL, '昌吉州文化和旅游局公开信息', '2026-05-19'),

(37, '喀纳斯景区', '阿勒泰', '新疆阿勒泰地区布尔津县',
  '集湖泊、河流、草原、森林、雪山于一体，以禾木晨雾和彩林秋色闻名的边境风景区。旺季需提前订住宿。',
  'https://upload.wikimedia.org/wikipedia/commons/c/cd/LakeKanas.jpg',
  245.00, 122.00, 1500, 890, '08:00-20:00（旺季，以景区公告为准）',
  48.6867, 87.0005, NULL, '阿勒泰地区文化和旅游局公开信息', '2026-05-19'),

(38, '元阳哈尼梯田', '红河', '云南省红河州元阳县',
  '世界文化遗产，哈尼族先民开凿的大规模梯田，以冬春水季日照云海倒影最为壮观，多依树观景台是核心打卡点。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/7/70/Terrace_field_yunnan_china_denoised.jpg/960px-Terrace_field_yunnan_china_denoised.jpg',
  100.00, 50.00, 2000, 1560, '08:00-18:00（以景区公告为准）',
  23.1161, 102.7756, NULL, '红河州文化和旅游局公开信息', '2026-05-19'),

(39, '石林风景区', '昆明', '云南省昆明市石林彝族自治县',
  '世界自然遗产，以喀斯特地貌形成的剑状石灰岩群落著称，被称为"天下第一奇观"。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Shilin_Yunnan_China_Shilin-Stone-Forest-03.jpg/960px-Shilin_Yunnan_China_Shilin-Stone-Forest-03.jpg',
  200.00, 100.00, 2000, 1240, '07:30-18:00（以景区公告为准）',
  24.7726, 103.2701, 'https://www.chinastoneforest.com/', '石林风景名胜区官网', '2026-05-19'),

(40, '龙门石窟', '洛阳', '河南省洛阳市南郊伊水两岸',
  '北魏至唐代皇家开凿的大型石窟群，世界文化遗产，奉先寺卢舍那大佛为代表性造像，规模宏大。',
  'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Longmen_Grottoes_3.jpg/960px-Longmen_Grottoes_3.jpg',
  90.00, 45.00, 2500, 1560, '08:00-17:30（以景区公告为准）',
  34.5604, 112.4741, 'https://www.longmen.gov.cn/', '龙门石窟景区官网', '2026-05-19'),

(41, '武夷山', '南平', '福建省南平市武夷山市',
  '世界文化与自然双重遗产，以丹霞地貌、碧水九曲和武夷岩茶产区著称，竹筏漂流体验极佳。',
  '/images/real/attractions/wuyi-mountain.jpg',
  140.00, 70.00, 1500, 1020, '07:30-18:00（以景区公告为准）',
  27.7494, 117.9855, 'https://www.wuyi.gov.cn/', '武夷山风景名胜区管委会官网', '2026-05-19'),

(42, '周庄古镇', '苏州', '江苏省苏州市昆山市周庄镇',
  '江南水乡代表古镇，以水道、石桥、明清民居和双桥著称，有"中国第一水乡"之称。早晨人少，建议8点前进入。',
  '/images/real/attractions/zhouzhuang.jpg',
  100.00, 50.00, 2000, 1460, '08:00-17:00（以景区公告为准）',
  31.1132, 120.8476, NULL, '周庄古镇景区管委会公开信息', '2026-05-19'),

(43, '夫子庙秦淮风光带', '南京', '江苏省南京市秦淮区贡院街',
  '以秦淮河沿岸历史文化街区为核心，涵盖夫子庙、贡院、乌衣巷等历史景观，是南京文化旅游核心区，多数区域免费开放。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/Night_View_of_Nanjing_Fuzimiao.jpg',
  0.00, 0.00, 9999, 9999, '全天开放（贡院等收费景点另行公告）',
  32.0211, 118.7834, NULL, '南京市文化和旅游局公开信息', '2026-05-19'),

(44, '西双版纳热带植物园', '西双版纳', '云南省西双版纳州勐腊县勐仑镇',
  '中国科学院直属热带植物科研基地，同时对公众开放，以物种多样性和热带雨林景观著称，是自然科普和度假的优选地。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/20251225_Banyan_in_the_Xishuangbanna_Tropical_Botanical_Garden,_Chinese_Academy_of_Sciences.jpg',
  80.00, 40.00, 2000, 1650, '08:00-18:00（以园区公告为准）',
  21.9158, 101.0253, 'https://www.xtbg.cas.cn/', '西双版纳热带植物园官网', '2026-05-19'),

(45, '崂山风景区', '青岛', '山东省青岛市崂山区',
  '道教名山，主峰巨峰海拔1132.7米，以海上仙山、清泉奇石和道教文化著称，是青岛近郊必游山岳景区。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/20240730_Dabiao_Mountain_of_Mount_Lao_01.jpg',
  80.00, 40.00, 2000, 1560, '06:30-17:00（以景区公告为准）',
  36.1654, 120.6028, 'https://www.laoshan.gov.cn/', '崂山区文化和旅游局', '2026-05-19'),

(46, '海螺沟冰川森林公园', '甘孜', '四川省甘孜州泸定县磨西镇',
  '以现代冰川、高山温泉和原始森林为核心景观，贡嘎山麓冰川可步行近距离接触，是四川高原特色景区。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/Hailuogou_glacier.JPG',
  82.00, 41.00, 1200, 820, '08:00-18:00（以景区公告为准）',
  29.5744, 102.0626, NULL, '海螺沟景区管委会公开信息', '2026-05-19'),

(47, '黄龙风景名胜区', '阿坝', '四川省阿坝州松潘县',
  '世界自然遗产，以彩池、雪山、峡谷、森林构成的景观组合闻名，核心景区彩池群层叠绵延，与九寨沟形成黄九环线。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/Huanglong_travertine_pools.jpg',
  150.00, 75.00, 1500, 960, '08:00-17:00（以景区公告为准，海拔高）',
  32.7502, 103.8165, NULL, '阿坝州文化和旅游局公开信息', '2026-05-19'),

(48, '武陵源·黄龙洞', '张家界', '湖南省张家界市武陵源区',
  '武陵源世界自然遗产核心区内的溶洞景区，以大规模石钟乳、石笋和地下河著称，是张家界地下景观的代表。',
  'https://commons.wikimedia.org/wiki/Special:Redirect/file/Huanglongdong.JPG',
  130.00, 65.00, 1000, 680, '08:00-17:30（以景区公告为准）',
  29.368, 110.5526, NULL, '武陵源景区管委会公开信息', '2026-05-19')

ON DUPLICATE KEY UPDATE
  `name`              = VALUES(`name`),
  `city`              = VALUES(`city`),
  `address`           = VALUES(`address`),
  `description`       = VALUES(`description`),
  `cover_img`         = VALUES(`cover_img`),
  `adult_price`       = VALUES(`adult_price`),
  `child_price`       = VALUES(`child_price`),
  `open_time`         = VALUES(`open_time`),
  `lat`               = VALUES(`lat`),
  `lng`               = VALUES(`lng`),
  `source_name`       = VALUES(`source_name`),
  `data_checked_date` = VALUES(`data_checked_date`);

INSERT IGNORE INTO `tm_tour_product` (`id`, `name`, `description`, `tour_type`, `departure_city`, `destination`, `duration`, `price`, `cover_img`, `source_name`, `source_url`, `data_checked_date`) VALUES
(1, '故宫博物院官方导览一日', '基于故宫博物院开放时间与官方导览信息整理，适合首次到访的中轴线游览。价格为演示服务费，不代表官方票价。', 0, '北京', '故宫博物院', '1天', 128.00, '/images/seed/beijing.svg', '故宫博物院官网', 'https://www.dpm.org.cn/Visit.html', '2026-05-19'),
(2, '颐和园昆明湖半日游', '基于颐和园开放时间与园区导览整理，覆盖东宫门、仁寿殿、长廊、昆明湖等节点。价格为演示服务费。', 0, '北京', '颐和园', '0.5天', 98.00, '/images/seed/beijing.svg', '颐和园官网', 'https://www.summerpalace.net.cn/visit.html', '2026-05-19'),
(3, '杭州西湖环湖一日游', '基于西湖景区公开信息整理，串联断桥、白堤、苏堤、花港观鱼和湖滨区域。价格为演示服务费。', 0, '杭州', '西湖', '1天', 118.00, '/images/seed/hangzhou.svg', '杭州西湖风景名胜区管委会', 'https://westlake.hangzhou.gov.cn/', '2026-05-19'),
(4, '黄山风景区经典两日游', '基于黄山风景区公开信息整理，覆盖云谷寺、始信峰、北海、光明顶、玉屏楼等常规节点。价格为演示服务费。', 1, '黄山', '黄山风景区', '2天1晚', 398.00, '/images/seed/mountain.svg', '黄山风景区管委会', 'https://hsgwh.huangshan.gov.cn/', '2026-05-19'),
(5, '九寨沟核心景点一日游', '基于九寨沟景区票务与服务信息整理，覆盖树正沟、日则沟、则查洼沟核心观景点。价格为演示服务费。', 0, '阿坝', '九寨沟风景名胜区', '1天', 268.00, '/images/seed/lake.svg', '九寨沟风景名胜区官网', 'https://www.jiuzhai.com/intelligent-service/tickets', '2026-05-19'),
(6, '桂林漓江游船一日游', '基于桂林文旅公开信息整理，围绕桂林至阳朔漓江游船线路设计。价格为演示服务费。', 0, '桂林', '漓江风景名胜区', '1天', 288.00, '/images/seed/guilin.svg', '桂林市文化广电和旅游局', 'https://wglj.guilin.gov.cn/', '2026-05-19');

INSERT IGNORE INTO `tm_tour_product` (`id`, `name`, `description`, `tour_type`, `departure_city`, `destination`, `duration`, `price`, `cover_img`, `source_name`, `source_url`, `data_checked_date`) VALUES
(7, '重庆山城夜景三日游', '结合重庆公开文旅信息和真实游客常用动线整理，覆盖解放碑、洪崖洞、李子坝、山城步道等节点。价格为演示服务费。', 1, '重庆', '重庆主城', '3天2晚', 468.00, '/images/seed/chongqing.svg', '重庆市文旅委公开信息/路线场景整理', 'https://whlyw.cq.gov.cn/', '2026-05-21'),
(8, '厦门鼓浪屿三日慢游', '结合鼓浪屿管委会公开信息和厦门经典慢游动线整理，覆盖鼓浪屿、沙坡尾、环岛路等节点。价格为演示服务费。', 1, '厦门', '厦门', '3天2晚', 498.00, '/images/seed/coast.svg', '鼓浪屿管委会公开信息/路线场景整理', 'https://gly.xm.gov.cn/', '2026-05-21'),
(9, '南京博物馆中山陵一日游', '基于携程南京目的地联想和南京钟山风景区公开信息整理，适合城市历史文化轻量游。价格为演示服务费。', 0, '南京', '南京', '1天', 158.00, '/images/seed/nanjing.svg', '携程目的地搜索/南京钟山风景区官网', 'https://zschina.nanjing.gov.cn/', '2026-05-21'),
(10, '苏州园林平江路一日游', '基于携程苏州目的地联想和拙政园公开信息整理，覆盖古典园林、平江路和山塘街。价格为演示服务费。', 0, '苏州', '苏州古城', '1天', 168.00, '/images/seed/garden.svg', '携程目的地搜索/拙政园官网', 'https://www.szzzy.cn/', '2026-05-21');

INSERT IGNORE INTO `tm_tour_product_step` (`id`, `product_id`, `day_no`, `sequence_no`, `place_name`, `attraction_id`, `stay_minutes`, `transport_note`, `source_url`) VALUES
(1, 1, 1, 1, '午门入院', 1, 30, '建议按预约时段入院', 'https://www.dpm.org.cn/Visit.html'),
(2, 1, 1, 2, '太和殿-中和殿-保和殿', 1, 90, '沿中轴线步行游览', 'https://www.dpm.org.cn/Visit.html'),
(3, 1, 1, 3, '乾清宫-交泰殿-坤宁宫', 1, 60, '继续沿中轴线步行', 'https://www.dpm.org.cn/Visit.html'),
(4, 1, 1, 4, '御花园-神武门出院', 1, 45, '从神武门离院后可衔接景山公园', 'https://www.dpm.org.cn/Visit.html'),
(5, 2, 1, 1, '东宫门', 2, 20, '入口与集合点', 'https://www.summerpalace.net.cn/visit.html'),
(6, 2, 1, 2, '仁寿殿-长廊', 2, 70, '园内步行', 'https://www.summerpalace.net.cn/visit.html'),
(7, 2, 1, 3, '昆明湖-十七孔桥', 2, 80, '湖区步行或游船以现场开放为准', 'https://www.summerpalace.net.cn/visit.html'),
(8, 3, 1, 1, '断桥残雪', 4, 30, '湖滨步行起点', 'https://westlake.hangzhou.gov.cn/'),
(9, 3, 1, 2, '白堤-孤山', 4, 80, '沿湖步行', 'https://westlake.hangzhou.gov.cn/'),
(10, 3, 1, 3, '苏堤-花港观鱼', 4, 120, '环湖公交/步行衔接', 'https://westlake.hangzhou.gov.cn/'),
(11, 4, 1, 1, '云谷寺索道上山', 8, 60, '索道开放以景区公告为准', 'https://hsgwh.huangshan.gov.cn/'),
(12, 4, 1, 2, '始信峰-北海', 8, 180, '山上步道游览', 'https://hsgwh.huangshan.gov.cn/'),
(13, 4, 2, 1, '光明顶日出', 8, 90, '需结合天气和住宿位置', 'https://hsgwh.huangshan.gov.cn/'),
(14, 4, 2, 2, '玉屏楼-迎客松', 8, 150, '步行后下山', 'https://hsgwh.huangshan.gov.cn/'),
(15, 5, 1, 1, '诺日朗游客中心', 7, 30, '景区观光车换乘', 'https://www.jiuzhai.com/intelligent-service/tickets'),
(16, 5, 1, 2, '五花海-珍珠滩', 7, 150, '日则沟核心景点', 'https://www.jiuzhai.com/intelligent-service/tickets'),
(17, 5, 1, 3, '长海-五彩池', 7, 120, '则查洼沟观光车衔接', 'https://www.jiuzhai.com/intelligent-service/tickets'),
(18, 6, 1, 1, '磨盘山/竹江码头登船', 9, 30, '码头和班次以当日通知为准', 'https://wglj.guilin.gov.cn/'),
(19, 6, 1, 2, '漓江游船航段', 9, 240, '桂林至阳朔典型游船线路', 'https://wglj.guilin.gov.cn/'),
(20, 6, 1, 3, '阳朔下船散步', 9, 90, '可衔接西街或返程交通', 'https://wglj.guilin.gov.cn/');

INSERT IGNORE INTO `tm_tour_product_step` (`id`, `product_id`, `day_no`, `sequence_no`, `place_name`, `attraction_id`, `stay_minutes`, `transport_note`, `source_url`) VALUES
(21, 7, 1, 1, '解放碑-八一好吃街', NULL, 120, '市中心步行，适合抵达日', 'https://whlyw.cq.gov.cn/'),
(22, 7, 1, 2, '洪崖洞-千厮门大桥夜景', 24, 120, '傍晚后步行或轨道交通前往', 'https://whlyw.cq.gov.cn/'),
(23, 7, 2, 1, '李子坝-鹅岭二厂', NULL, 150, '轨道交通二号线衔接', 'https://www.xiaohongshu.com/search_result/69527e29000000001e0104e3?xsec_token=AB6Nmx2NPTIida2wNAZKoe5hcIEHgoQBrmGY5RMJvBJF4=&xsec_source='),
(24, 7, 2, 2, '山城步道-十八梯', NULL, 180, '坡道较多，建议轻装', 'https://whlyw.cq.gov.cn/'),
(25, 8, 1, 1, '中山路-八市-沙坡尾', NULL, 240, '厦门岛内步行和公交衔接', 'https://www.xiaohongshu.com/search_result/69d2089a000000002103baff?xsec_token=ABa2URARwU2dy6rXtRtvuFSOOlogh_zRR6bspLh5r2M-8=&xsec_source='),
(26, 8, 2, 1, '鼓浪屿街巷慢游', 21, 300, '轮渡票和上岛时间需提前确认', 'https://gly.xm.gov.cn/'),
(27, 8, 3, 1, '南普陀-白城沙滩-环岛路', NULL, 240, '公交/骑行衔接，注意天气', 'https://www.xiaohongshu.com/search_result/69d2089a000000002103baff?xsec_token=ABa2URARwU2dy6rXtRtvuFSOOlogh_zRR6bspLh5r2M-8=&xsec_source='),
(28, 9, 1, 1, '南京博物院', NULL, 180, '热门展馆建议提前预约', 'https://you.ctrip.com/sight/%E5%8D%97%E4%BA%AC12/4190936.html'),
(29, 9, 1, 2, '中山陵', 22, 150, '景区内步行，注意闭馆日', 'https://zschina.nanjing.gov.cn/'),
(30, 10, 1, 1, '拙政园', 23, 150, '早到避开客流高峰', 'https://www.szzzy.cn/'),
(31, 10, 1, 2, '平江路', NULL, 120, '古城步行街区', 'https://you.ctrip.com/place/%E8%8B%8F%E5%B7%9E14.html'),
(32, 10, 1, 3, '山塘街夜游', NULL, 120, '傍晚后游览更适合拍照', 'https://you.ctrip.com/sight/%E8%8B%8F%E5%B7%9E14/8168464.html');

INSERT INTO `tm_tour_schedule`
  (`product_id`, `travel_date`, `unit_price`, `total_stock`, `available_stock`, `status`)
SELECT
  seed.`product_id`, seed.`travel_date`, seed.`unit_price`, seed.`total_stock`, seed.`available_stock`, seed.`status`
FROM (
  SELECT 1 AS `product_id`, DATE_ADD(CURRENT_DATE, INTERVAL 7 DAY) AS `travel_date`, 128.00 AS `unit_price`, 30 AS `total_stock`, 30 AS `available_stock`, 1 AS `status`
  UNION ALL SELECT 1, DATE_ADD(CURRENT_DATE, INTERVAL 14 DAY), 138.00, 30, 30, 1
  UNION ALL SELECT 3, DATE_ADD(CURRENT_DATE, INTERVAL 8 DAY), 118.00, 25, 25, 1
  UNION ALL SELECT 3, DATE_ADD(CURRENT_DATE, INTERVAL 15 DAY), 128.00, 25, 25, 1
  UNION ALL SELECT 4, DATE_ADD(CURRENT_DATE, INTERVAL 9 DAY), 398.00, 20, 20, 1
  UNION ALL SELECT 4, DATE_ADD(CURRENT_DATE, INTERVAL 16 DAY), 428.00, 20, 20, 1
  UNION ALL SELECT 7, DATE_ADD(CURRENT_DATE, INTERVAL 10 DAY), 468.00, 20, 20, 1
  UNION ALL SELECT 8, DATE_ADD(CURRENT_DATE, INTERVAL 11 DAY), 498.00, 20, 20, 1
  UNION ALL SELECT 9, DATE_ADD(CURRENT_DATE, INTERVAL 12 DAY), 158.00, 30, 30, 1
  UNION ALL SELECT 10, DATE_ADD(CURRENT_DATE, INTERVAL 13 DAY), 168.00, 30, 30, 1
) AS seed
WHERE NOT EXISTS (
  SELECT 1
  FROM `tm_tour_schedule` AS existing
  WHERE existing.`product_id` = seed.`product_id`
    AND existing.`travel_date` >= CURRENT_DATE
    AND existing.`status` = 1
);

INSERT IGNORE INTO `tm_coupon` (`name`, `description`, `category`, `discount_type`, `discount_value`, `min_amount`, `expire_date`, `stock`, `status`) VALUES
('新用户专享', '新用户首单立减50元', 'all', 0, 50.00, 200.00, '2026-12-31 23:59:59', 200, 0),
('机票满减券', '机票订单满500减30', 'flight', 0, 30.00, 500.00, '2026-12-31 23:59:59', 150, 0),
('酒店9折券', '酒店订单享9折优惠', 'hotel', 1, 0.90, 0.00, '2026-12-31 23:59:59', 100, 0),
('火车票85折', '火车票订单享85折', 'train', 1, 0.85, 100.00, '2026-12-31 23:59:59', 80, 0);
