-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: ops demo seed data for local integration and E2E only.

SET NAMES utf8mb4;
USE `travelmate_ops`;

INSERT IGNORE INTO `sys_sensitive_word` (`word`, `level`) VALUES
('赌博', 3), ('诈骗', 3), ('色情', 3), ('暴力', 2),
('广告', 1), ('代购', 1), ('刷单', 2);
