[CmdletBinding()]
param(
    [string]$SourceSql,
    [string]$OutputDirectory
)

$ErrorActionPreference = 'Stop'

if ([string]::IsNullOrWhiteSpace($SourceSql)) {
    $SourceSql = Join-Path $PSScriptRoot '..\docs\sql\init.sql'
}
if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $PSScriptRoot '..\microservices\sql'
}

$sourcePath = (Resolve-Path -LiteralPath $SourceSql).Path
$outputPath = [IO.Path]::GetFullPath($OutputDirectory)
$sql = [IO.File]::ReadAllText($sourcePath)
$tablePattern = '(?ms)^CREATE TABLE IF NOT EXISTS `(?<name>[^`]+)`\s*\(.*?^\) ENGINE=.*?;\s*'
$matches = [regex]::Matches($sql, $tablePattern)
$insertPattern = '(?ms)^INSERT(?:\s+IGNORE)?\s+INTO\s+`(?<name>[^`]+)`.*?;\s*'
$insertMatches = [regex]::Matches($sql, $insertPattern)

if ($matches.Count -eq 0) {
    throw "No CREATE TABLE statements could be parsed from $sourcePath."
}

$tableSql = [ordered]@{}
foreach ($match in $matches) {
    $name = $match.Groups['name'].Value
    if ($tableSql.Contains($name)) {
        throw "Duplicate CREATE TABLE statement in source SQL: $name"
    }
    $tableSql[$name] = $match.Value.Trim()
}

$seedSql = @{}
foreach ($match in $insertMatches) {
    $name = $match.Groups['name'].Value
    if (-not $seedSql.ContainsKey($name)) {
        $seedSql[$name] = [Collections.Generic.List[string]]::new()
    }
    $seedSql[$name].Add($match.Value.Trim())
}

$services = [ordered]@{
    identity = @('tm_user', 'tm_passenger', 'tm_follow')
    traffic  = @('tm_flight', 'tm_train', 'tm_traffic_order', 'tm_train_waitlist', 'tm_price_history', 'tm_traffic_outbox_event')
    local    = @(
        'tm_hotel', 'tm_hotel_room', 'tm_hotel_order',
        'tm_attraction', 'tm_attraction_order', 'tm_destination',
        'tm_review', 'tm_reply', 'tm_review_report',
        'tm_tour_product', 'tm_tour_product_step',
        'tm_coupon', 'tm_user_coupon', 'tm_local_outbox_event'
    )
    ai       = @(
        'tm_ai_plan', 'tm_ai_chat', 'tm_notification',
        'tm_private_message', 'tm_private_contact', 'tm_ai_consumed_event'
    )
    community = @('tm_post', 'tm_comment', 'tm_like')
    ops       = @('sys_log', 'sys_sensitive_word')
}

$databases = @{
    identity = 'travelmate_identity'
    traffic  = 'travelmate_traffic'
    local    = 'travelmate_local'
    ai       = 'travelmate_ai'
    community = 'travelmate_community'
    ops       = 'travelmate_ops'
}

# Extract only self-contained lookup data required by real E2E scenarios.
# Tests create stateful data such as users, orders, and reviews themselves.
$seedTables = @{
    identity = @()
    traffic  = @('tm_flight', 'tm_train', 'tm_price_history')
    local    = @('tm_hotel', 'tm_hotel_room', 'tm_attraction', 'tm_tour_product', 'tm_tour_product_step', 'tm_coupon')
    ai       = @()
    community = @('tm_post')
    ops       = @('sys_sensitive_word')
}

$owners = @{}
foreach ($service in $services.Keys) {
    foreach ($table in $services[$service]) {
        if (-not $tableSql.Contains($table)) {
            throw "Table $table declared by service $service does not exist in $sourcePath."
        }
        if ($owners.ContainsKey($table)) {
            throw "Table $table is assigned to both $($owners[$table]) and $service."
        }
        $owners[$table] = $service
    }
}

New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
$encoding = [Text.UTF8Encoding]::new($false)

foreach ($service in $services.Keys) {
    $database = $databases[$service]
    $blocks = foreach ($table in $services[$service]) {
        "-- $table`r`n$($tableSql[$table])"
    }
    $header = @"
-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: $service
-- This file contains schema only; demo seed data remains in the monolith baseline.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS ``$database`` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ``$database``;

"@
    $target = Join-Path $outputPath "$service-schema.sql"
    [IO.File]::WriteAllText($target, $header + ($blocks -join "`r`n`r`n") + "`r`n", $encoding)

    $seedBlocks = foreach ($table in $seedTables[$service]) {
        if ($seedSql.ContainsKey($table)) {
            $seedSql[$table]
        }
    }
    $seedHeader = @"
-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: $service demo seed data for local integration and E2E only.

SET NAMES utf8mb4;
USE ``$database``;

"@
    $seedTarget = Join-Path $outputPath "$service-seed.sql"
    $seedContent = $seedHeader.TrimEnd()
    if ($seedBlocks.Count -gt 0) {
        $seedContent += "`r`n`r`n" + ($seedBlocks -join "`r`n`r`n")
    }
    [IO.File]::WriteAllText($seedTarget, $seedContent + "`r`n", $encoding)
    Write-Output "$service -> $target ($($services[$service].Count) tables), $seedTarget ($($seedBlocks.Count) seed blocks)"
}
