[CmdletBinding()]
param(
    [string]$SourceSql = (Join-Path $PSScriptRoot '..\docs\sql\init.sql'),
    [string]$OutputDirectory = (Join-Path $PSScriptRoot '..\microservices\sql')
)

$ErrorActionPreference = 'Stop'

$sourcePath = (Resolve-Path -LiteralPath $SourceSql).Path
$outputPath = [IO.Path]::GetFullPath($OutputDirectory)
$sql = [IO.File]::ReadAllText($sourcePath)
$tablePattern = '(?ms)^CREATE TABLE IF NOT EXISTS `(?<name>[^`]+)`\s*\(.*?^\) ENGINE=.*?;\s*'
$matches = [regex]::Matches($sql, $tablePattern)

if ($matches.Count -eq 0) {
    throw "未能从 $sourcePath 解析任何 CREATE TABLE 语句。"
}

$tableSql = [ordered]@{}
foreach ($match in $matches) {
    $name = $match.Groups['name'].Value
    if ($tableSql.Contains($name)) {
        throw "事实源中出现重复建表语句：$name"
    }
    $tableSql[$name] = $match.Value.Trim()
}

$services = [ordered]@{
    identity = @('tm_user', 'tm_passenger', 'tm_follow')
    traffic  = @('tm_flight', 'tm_train', 'tm_traffic_order', 'tm_train_waitlist', 'tm_price_history', 'tm_traffic_outbox_event')
    local    = @(
        'tm_hotel', 'tm_hotel_room', 'tm_hotel_order',
        'tm_attraction', 'tm_attraction_order', 'tm_destination',
        'tm_review', 'tm_reply', 'tm_review_report',
        'tm_tour_product', 'tm_tour_product_step',
        'tm_coupon', 'tm_user_coupon', 'tm_local_outbox_event'
    )
    ai       = @(
        'tm_ai_plan', 'tm_ai_chat', 'tm_notification',
        'tm_private_message', 'tm_private_contact', 'tm_ai_consumed_event'
    )
}

$databases = @{
    identity = 'travelmate_identity'
    traffic  = 'travelmate_traffic'
    local    = 'travelmate_local'
    ai       = 'travelmate_ai'
}

$owners = @{}
foreach ($service in $services.Keys) {
    foreach ($table in $services[$service]) {
        if (-not $tableSql.Contains($table)) {
            throw "服务 $service 声明的表 $table 不存在于 $sourcePath。"
        }
        if ($owners.ContainsKey($table)) {
            throw "表 $table 同时归属 $($owners[$table]) 和 $service。"
        }
        $owners[$table] = $service
    }
}

New-Item -ItemType Directory -Force -Path $outputPath | Out-Null
$encoding = [Text.UTF8Encoding]::new($false)

foreach ($service in $services.Keys) {
    $database = $databases[$service]
    $blocks = foreach ($table in $services[$service]) {
        "-- $table`r`n$($tableSql[$table])"
    }
    $header = @"
-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: $service
-- This file contains schema only; demo seed data remains in the monolith baseline.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS ``$database`` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ``$database``;

"@
    $target = Join-Path $outputPath "$service-schema.sql"
    [IO.File]::WriteAllText($target, $header + ($blocks -join "`r`n`r`n") + "`r`n", $encoding)
    Write-Output "$service -> $target ($($services[$service].Count) tables)"
}
