-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: identity demo seed data for local integration and E2E only.

SET NAMES utf8mb4;
USE `travelmate_identity`;
