-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: local
-- This file contains schema only; demo seed data remains in the monolith baseline.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `travelmate_local` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `travelmate_local`;
-- tm_hotel
CREATE TABLE IF NOT EXISTS `tm_hotel` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '酒店名称',
  `city` VARCHAR(50) NOT NULL COMMENT '所在城市',
  `address` VARCHAR(255) NOT NULL COMMENT '详细地址',
  `star_rating` TINYINT(1) DEFAULT '3' COMMENT '星级',
  `description` TEXT COMMENT '酒店介绍',
  `cover_img` VARCHAR(500) COMMENT '封面图',
  `lat` DECIMAL(10,6) COMMENT '纬度',
  `lng` DECIMAL(10,6) COMMENT '经度',
  `avg_price` DECIMAL(10,2) DEFAULT '0' COMMENT '平均价格',
  `score` DECIMAL(3,1) DEFAULT '4.5' COMMENT '评分',
  `status` TINYINT(1) DEFAULT '1' COMMENT '1-营业 0-停业',
  `source_name` VARCHAR(100) DEFAULT NULL COMMENT '数据来源名称',
  `source_url` VARCHAR(500) DEFAULT NULL COMMENT '数据来源URL',
  `data_checked_date` DATE DEFAULT NULL COMMENT '数据核验日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='酒店基础信息表';

-- tm_hotel_room
CREATE TABLE IF NOT EXISTS `tm_hotel_room` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `hotel_id` BIGINT NOT NULL COMMENT '所属酒店ID',
  `room_type` VARCHAR(50) NOT NULL COMMENT '房型名称(大床房/双床房/套房)',
  `bed_type` VARCHAR(50) COMMENT '床型',
  `area` INT COMMENT '面积(平方米)',
  `price` DECIMAL(10,2) NOT NULL COMMENT '每晚价格',
  `total_rooms` INT NOT NULL DEFAULT '10' COMMENT '总房间数',
  `available_rooms` INT NOT NULL DEFAULT '10' COMMENT '可用房间数',
  `images` VARCHAR(500) COMMENT '房型图片URLs(逗号分隔)',
  `facilities` VARCHAR(500) COMMENT '设施(WiFi/空调/浴缸等逗号分隔)',
  `status` TINYINT(1) DEFAULT '1' COMMENT '1-可预订 0-不可用',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='酒店房型表';

-- tm_hotel_order
CREATE TABLE IF NOT EXISTS `tm_hotel_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `hotel_id` BIGINT NOT NULL COMMENT '酒店ID',
  `room_id` BIGINT NOT NULL COMMENT '房型ID',
  `hotel_name` VARCHAR(100) NOT NULL COMMENT '酒店名称',
  `room_type` VARCHAR(50) NOT NULL COMMENT '房型',
  `room_count` INT NOT NULL DEFAULT '1' COMMENT '预订房间数',
  `check_in_date` DATE NOT NULL COMMENT '入住日期',
  `check_out_date` DATE NOT NULL COMMENT '退房日期',
  `nights` INT NOT NULL COMMENT '入住天数',
  `guest_name` VARCHAR(50) NOT NULL COMMENT '入住人姓名',
  `guest_phone` VARCHAR(20) NOT NULL COMMENT '联系电话',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '订单总金额',
  `status` TINYINT(1) DEFAULT '0' COMMENT '0-待支付, 1-已支付, 2-入住中, 3-已完成, 4-已取消/已退款, 5-退款申请中',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `pay_time` DATETIME DEFAULT NULL,
  `deleted` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='酒店订单表';

-- tm_attraction
CREATE TABLE IF NOT EXISTS `tm_attraction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '景点名称',
  `city` VARCHAR(50) NOT NULL COMMENT '所在城市',
  `address` VARCHAR(255) COMMENT '详细地址',
  `description` TEXT COMMENT '景点介绍',
  `cover_img` VARCHAR(500) COMMENT '封面图',
  `adult_price` DECIMAL(10,2) NOT NULL COMMENT '成人票价',
  `child_price` DECIMAL(10,2) DEFAULT '0' COMMENT '儿童票价',
  `total_tickets` INT DEFAULT '1000' COMMENT '每日总票数',
  `available_tickets` INT DEFAULT '1000' COMMENT '当日余票',
  `open_time` VARCHAR(50) COMMENT '开放时间',
  `lat` DECIMAL(10,6) COMMENT '纬度',
  `lng` DECIMAL(10,6) COMMENT '经度',
  `status` TINYINT(1) DEFAULT '1' COMMENT '1-正常 0-暂停开放',
  `official_url` VARCHAR(500) DEFAULT NULL COMMENT '官方/政府来源URL',
  `source_name` VARCHAR(100) DEFAULT NULL COMMENT '数据来源名称',
  `data_checked_date` DATE DEFAULT NULL COMMENT '数据核验日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='景点门票表';

-- tm_attraction_order
CREATE TABLE IF NOT EXISTS `tm_attraction_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_no` VARCHAR(50) NOT NULL COMMENT '订单编号',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `attraction_id` BIGINT NOT NULL COMMENT '景点ID',
  `attraction_name` VARCHAR(100) NOT NULL COMMENT '景点名称快照',
  `city` VARCHAR(50) DEFAULT NULL COMMENT '城市快照',
  `adult_count` INT NOT NULL DEFAULT '0' COMMENT '成人票数量',
  `child_count` INT NOT NULL DEFAULT '0' COMMENT '儿童票数量',
  `ticket_count` INT NOT NULL DEFAULT '1' COMMENT '总票数',
  `guest_name` VARCHAR(50) NOT NULL COMMENT '游客姓名',
  `guest_phone` VARCHAR(20) NOT NULL COMMENT '游客手机号',
  `amount` DECIMAL(10,2) NOT NULL COMMENT '订单金额',
  `status` TINYINT(1) DEFAULT '1' COMMENT '1-已支付/待核销, 2-已核销, 4-已取消/已退款',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '购票时间',
  `deleted` TINYINT(1) DEFAULT '0' COMMENT '逻辑删除: 0-未删除, 1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`order_no`),
  KEY `idx_user_create_time` (`user_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='景点门票订单表';

-- tm_destination
CREATE TABLE IF NOT EXISTS `tm_destination` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `slug` VARCHAR(80) NOT NULL COMMENT '城市URL标识',
  `name` VARCHAR(80) NOT NULL COMMENT '城市名称',
  `country` VARCHAR(80) DEFAULT '中国' COMMENT '国家/地区',
  `tag` VARCHAR(80) NOT NULL COMMENT '城市标签',
  `keywords` VARCHAR(300) DEFAULT NULL COMMENT '关键词，逗号或竖线分隔',
  `img` VARCHAR(500) NOT NULL COMMENT '封面图URL',
  `desc` VARCHAR(500) NOT NULL COMMENT '短描述',
  `intro` TEXT NOT NULL COMMENT '城市介绍',
  `highlights` TEXT DEFAULT NULL COMMENT '城市亮点，竖线或换行分隔',
  `culture` TEXT DEFAULT NULL COMMENT '旅行气质',
  `best_season` VARCHAR(500) DEFAULT NULL COMMENT '推荐季节',
  `transport` VARCHAR(500) DEFAULT NULL COMMENT '交通建议',
  `source_name` VARCHAR(255) DEFAULT NULL COMMENT '资料来源名称',
  `source_url` VARCHAR(500) DEFAULT NULL COMMENT '资料来源URL',
  `sort_order` INT DEFAULT 100 COMMENT '排序值',
  `status` TINYINT(1) DEFAULT '1' COMMENT '0-下线, 1-展示',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_destination_slug` (`slug`),
  KEY `idx_destination_status_sort` (`status`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='热门城市资料表';

-- tm_review
CREATE TABLE IF NOT EXISTS `tm_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `target_id` BIGINT NOT NULL COMMENT '评价对象ID(酒店/景点)',
  `target_type` TINYINT(1) NOT NULL COMMENT '0-酒店, 1-景点',
  `order_id` BIGINT COMMENT '关联订单ID',
  `rating` TINYINT(1) NOT NULL COMMENT '评分(1-5)',
  `content` TEXT COMMENT '评价内容',
  `images` VARCHAR(500) COMMENT '图片URLs',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评价表';

-- tm_reply
CREATE TABLE IF NOT EXISTS `tm_reply` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_id` BIGINT NOT NULL COMMENT '评价ID',
  `user_id` BIGINT NOT NULL COMMENT '回复者ID',
  `content` VARCHAR(1000) NOT NULL COMMENT '回复内容',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `deleted` TINYINT(1) DEFAULT '0' COMMENT '0=正常, 1=已删除',
  PRIMARY KEY (`id`),
  INDEX `idx_review_id` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评价回复表';

-- tm_review_report
CREATE TABLE IF NOT EXISTS `tm_review_report` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `review_id` BIGINT NOT NULL COMMENT '评价ID',
  `reporter_id` BIGINT NOT NULL COMMENT '举报者ID',
  `reason` VARCHAR(200) DEFAULT NULL COMMENT '举报原因',
  `status` TINYINT(1) DEFAULT '0' COMMENT '0=待处理, 1=已处理',
  `handle_remark` VARCHAR(300) DEFAULT NULL COMMENT '处理备注',
  `handle_time` DATETIME DEFAULT NULL COMMENT '处理时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_review_id` (`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='评价举报表';

-- tm_tour_product
CREATE TABLE IF NOT EXISTS `tm_tour_product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '产品名称',
  `description` VARCHAR(500) DEFAULT NULL COMMENT '描述',
  `tour_type` TINYINT(1) DEFAULT '0' COMMENT '0=一日游, 1=周边游',
  `departure_city` VARCHAR(50) DEFAULT NULL COMMENT '出发城市',
  `destination` VARCHAR(100) DEFAULT NULL COMMENT '目的地',
  `duration` VARCHAR(20) DEFAULT NULL COMMENT '行程时长',
  `price` DECIMAL(10,2) DEFAULT '0.00' COMMENT '价格',
  `cover_img` VARCHAR(500) DEFAULT NULL COMMENT '封面图',
  `status` TINYINT(1) DEFAULT '1' COMMENT '0=下线, 1=上线',
  `source_name` VARCHAR(100) DEFAULT NULL COMMENT '数据来源名称',
  `source_url` VARCHAR(500) DEFAULT NULL COMMENT '数据来源URL',
  `data_checked_date` DATE DEFAULT NULL COMMENT '数据核验日期',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='一日游/周边游产品表';

-- tm_tour_product_step
CREATE TABLE IF NOT EXISTS `tm_tour_product_step` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `product_id` BIGINT NOT NULL COMMENT '所属行程产品ID',
  `day_no` INT NOT NULL DEFAULT 1 COMMENT '第几天',
  `sequence_no` INT NOT NULL COMMENT '当天顺序',
  `place_name` VARCHAR(100) NOT NULL COMMENT '游览节点',
  `attraction_id` BIGINT DEFAULT NULL COMMENT '关联景点ID',
  `stay_minutes` INT DEFAULT NULL COMMENT '建议停留分钟数',
  `transport_note` VARCHAR(200) DEFAULT NULL COMMENT '交通/衔接说明',
  `source_url` VARCHAR(500) DEFAULT NULL COMMENT '节点来源URL',
  PRIMARY KEY (`id`),
  KEY `idx_tour_step_product` (`product_id`, `day_no`, `sequence_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='一日游/周边游行程节点表';

-- tm_coupon
CREATE TABLE IF NOT EXISTS `tm_coupon` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT '优惠券名称',
  `description` VARCHAR(200) DEFAULT NULL COMMENT '描述',
  `category` VARCHAR(20) DEFAULT 'all' COMMENT '使用类别：all=通用, flight=机票, train=火车票, hotel=酒店',
  `discount_type` TINYINT(1) DEFAULT '0' COMMENT '0=满减, 1=折扣',
  `discount_value` DECIMAL(10,2) DEFAULT '0.00' COMMENT '减免金额或折扣比例',
  `min_amount` DECIMAL(10,2) DEFAULT '0.00' COMMENT '最低消费金额',
  `expire_date` DATETIME DEFAULT NULL COMMENT '过期时间',
  `stock` INT DEFAULT '100' COMMENT '可领取数量',
  `status` TINYINT(1) DEFAULT '0' COMMENT '0=有效, 1=已过期',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠券表';

-- tm_user_coupon
CREATE TABLE IF NOT EXISTS `tm_user_coupon` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `coupon_id` BIGINT NOT NULL COMMENT '优惠券ID',
  `status` TINYINT(1) DEFAULT '0' COMMENT '0=未使用, 1=已使用, 2=已过期',
  `received_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `used_time` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`user_id`),
  INDEX `idx_coupon_id` (`coupon_id`),
  UNIQUE KEY `uk_user_coupon` (`user_id`, `coupon_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户优惠券关联表';

-- tm_local_outbox_event
CREATE TABLE IF NOT EXISTS `tm_local_outbox_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(36) NOT NULL COMMENT '全局事件ID',
  `aggregate_type` VARCHAR(50) NOT NULL COMMENT '聚合类型',
  `aggregate_id` VARCHAR(100) NOT NULL COMMENT '聚合ID',
  `event_type` VARCHAR(100) NOT NULL COMMENT '事件类型',
  `payload` JSON NOT NULL COMMENT '事件负载',
  `status` TINYINT NOT NULL DEFAULT '0' COMMENT '0-待投递 1-已投递 2-死信 3-投递中',
  `retry_count` INT NOT NULL DEFAULT '0',
  `next_retry_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_error` VARCHAR(500) DEFAULT NULL,
  `published_time` DATETIME DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_local_outbox_event_id` (`event_id`),
  KEY `idx_local_outbox_pending` (`status`, `next_retry_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='本地生活服务事务Outbox';
