-- AUTO-GENERATED by scripts/Generate-MicroserviceSchemas.ps1
-- Source: docs/sql/init.sql
-- Service: ops
-- This file contains schema only; demo seed data remains in the monolith baseline.

SET NAMES utf8mb4;
CREATE DATABASE IF NOT EXISTS `travelmate_ops` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `travelmate_ops`;
-- sys_log
CREATE TABLE IF NOT EXISTS `sys_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT COMMENT '操作用户ID',
  `username` VARCHAR(50) COMMENT '操作用户名',
  `operation` VARCHAR(200) COMMENT '操作描述',
  `method` VARCHAR(200) COMMENT '请求方法',
  `params` TEXT COMMENT '请求参数',
  `ip` VARCHAR(50) COMMENT '请求IP',
  `time_ms` BIGINT COMMENT '执行耗时(ms)',
  `status` TINYINT(1) DEFAULT '1' COMMENT '0-失败, 1-成功',
  `error_msg` TEXT COMMENT '错误信息',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统操作日志表';

-- sys_sensitive_word
CREATE TABLE IF NOT EXISTS `sys_sensitive_word` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(100) NOT NULL COMMENT '敏感词',
  `level` TINYINT(1) DEFAULT '1' COMMENT '1-轻度, 2-中度, 3-严重',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_word` (`word`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='敏感词表';
